In [1]:
import pandas as pd
import requests

df_confirm = pd.read_csv ('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
df_death = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')

In [ ]:
#@title Default title text
df_death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/15/22,4/16/22,4/17/22,4/18/22,4/19/22,4/20/22,4/21/22,4/22/22,4/23/22,4/24/22
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7676,7676,7678,7679,7680,7680,7680,7680,7681,7682
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3495,3496,3496,3496,3496,3496,3496,3496,3496,3496
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6874,6874,6874,6874,6874,6874,6874,6874,6874,6875
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,153,153,153,153,153,153,153,153,153,153
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5656,5656,5656,5656,5657,5657,5657,5657,5657,5657
280,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
281,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2148,2148,2148,2148,2148,2148,2148,2148,2148,2149
282,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,3970,3973,3973,3973,3973,3973,3974,3974,3974,3974
283,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5462,5462,5463,5464,5464,5466,5467,5468,5468,5468

Warning: Total number of columns (828) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
sum(df_confirm,df_death)

UFuncTypeError: ignored

In [2]:
df_death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/16/22,4/17/22,4/18/22,4/19/22,4/20/22,4/21/22,4/22/22,4/23/22,4/24/22,4/25/22
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7676,7678,7679,7680,7680,7680,7680,7681,7682,7683
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3496,3496,3496,3496,3496,3496,3496,3496,3496,3496
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6874,6874,6874,6874,6874,6874,6874,6874,6875,6875
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,153,153,153,153,153,153,153,153,153,153
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5656,5656,5656,5657,5657,5657,5657,5657,5657,5657
280,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
281,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2148,2148,2148,2148,2148,2148,2148,2148,2149,2149
282,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,3973,3973,3973,3973,3973,3974,3974,3974,3974,3976
283,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5462,5463,5464,5464,5466,5467,5468,5468,5468,5468

Warning: Total number of columns (829) exceeds max_columns (20) limiting to first (20) columns.

In [5]:
import pandas as pd
import requests

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=TSLA&datatype=json&apikey=DRDU0ACD89IZ5H2D'
r_stock_price = requests.get(url)
data_stock_price = r_stock_price.json()

print(data_stock_price)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'TSLA', '3. Last Refreshed': '2022-04-25', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2022-04-25': {'1. open': '978.9700', '2. high': '1008.6200', '3. low': '975.3000', '4. close': '998.0200', '5. volume': '22593647'}, '2022-04-22': {'1. open': '1014.9100', '2. high': '1034.8500', '3. low': '994.0001', '4. close': '1005.0500', '5. volume': '23232186'}, '2022-04-21': {'1. open': '1074.7300', '2. high': '1092.2200', '3. low': '996.4150', '4. close': '1008.7800', '5. volume': '35138779'}, '2022-04-20': {'1. open': '1030.0000', '2. high': '1034.0000', '3. low': '975.2501', '4. close': '977.2000', '5. volume': '21616141'}, '2022-04-19': {'1. open': '1005.0600', '2. high': '1034.9400', '3. low': '995.3250', '4. close': '1028.1500', '5. volume': '16615944'}, '2022-04-18': {'1. open': '989.0300', '2. high': '1014.9200', '3. low': '973.4100', '4. close': '1004.2900', '5. volume': '17238407'}, '2022-04-14': {'1. open': '999.2900', '2. high': '1012.7099', '3. low': '982.1900', '4. close': '985.0000', '5. volume': '19474135'}, '2022-04-13': {'1. open': '981.0750', '2. high': '1026.2400', '3. low': '973.0970', '4. close': '1022.3700', '5. volume': '18373737'}, '2022-04-12': {'1. open': '997.6400', '2. high': '1021.1921', '3. low': '976.6001', '4. close': '986.9500', '5. volume': '21992032'}, '2022-04-11': {'1. open': '980.4000', '2. high': '1008.4681', '3. low': '974.6400', '4. close': '975.9300', '5. volume': '19785735'}, '2022-04-08': {'1. open': '1043.2100', '2. high': '1048.4400', '3. low': '1022.4350', '4. close': '1025.4900', '5. volume': '18337896'}, '2022-04-07': {'1. open': '1052.3900', '2. high': '1076.5900', '3. low': '1021.5401', '4. close': '1057.2600', '5. volume': '26482353'}, '2022-04-06': {'1. open': '1073.4700', '2. high': '1079.0000', '3. low': '1027.7000', '4. close': '1045.7600', '5. volume': '29782845'}, '2022-04-05': {'1. open': '1136.3000', '2. high': '1152.8700', '3. low': '1087.3000', '4. close': '1091.2600', '5. volume': '26192187'}, '2022-04-04': {'1. open': '1089.3800', '2. high': '1149.9100', '3. low': '1072.5300', '4. close': '1145.4500', '5. volume': '27392567'}, '2022-04-01': {'1. open': '1081.1500', '2. high': '1094.7500', '3. low': '1066.6400', '4. close': '1084.5900', '5. volume': '18087741'}, '2022-03-31': {'1. open': '1094.5700', '2. high': '1103.1399', '3. low': '1076.6410', '4. close': '1077.6000', '5. volume': '16330919'}, '2022-03-30': {'1. open': '1091.1700', '2. high': '1113.9500', '3. low': '1084.0000', '4. close': '1093.9900', '5. volume': '19955002'}, '2022-03-29': {'1. open': '1107.9900', '2. high': '1114.7700', '3. low': '1073.1100', '4. close': '1099.5700', '5. volume': '24538273'}, '2022-03-28': {'1. open': '1065.1000', '2. high': '1097.8799', '3. low': '1053.6000', '4. close': '1091.8400', '5. volume': '34168693'}, '2022-03-25': {'1. open': '1008.0000', '2. high': '1021.7999', '3. low': '997.3201', '4. close': '1010.6400', '5. volume': '20496893'}, '2022-03-24': {'1. open': '1009.7300', '2. high': '1024.4900', '3. low': '988.8000', '4. close': '1013.9200', '5. volume': '22973626'}, '2022-03-23': {'1. open': '979.9400', '2. high': '1040.7000', '3. low': '976.4000', '4. close': '999.1100', '5. volume': '40225383'}, '2022-03-22': {'1. open': '930.0000', '2. high': '997.8600', '3. low': '921.7500', '4. close': '993.9800', '5. volume': '34882278'}, '2022-03-21': {'1. open': '914.9800', '2. high': '942.8500', '3. low': '907.0900', '4. close': '921.1600', '5. volume': '26640958'}, '2022-03-18': {'1. open': '874.4900', '2. high': '907.8500', '3. low': '867.3900', '4. close': '905.3900', '5. volume': '33443159'}, '2022-03-17': {'1. open': '830.9900', '2. high': '875.0000', '3. low': '825.7178', '4. close': '871.6000', '5. volume': '22194324'}, '2022-03-16': {'1. open': '809.0000', '2. high': '842.0000', '3. low': '802.2601', '4. close': '840.2300', '5. volume': '28009607'}, '2022-03-15': {'1. open': '775.2700', '2. high': '805.5700', '3. low': '756.5700', '4. close': '801.8900', '5. volume': '22280381'}, '2022-03-14': {'1. open': '780.6100', '2. high': '800.7000', '3. low': '756.0400', '4. close': '766.3700', '5. volume': '23717421'}, '2022-03-11': {'1. open': '840.1970', '2. high': '843.8020', '3. low': '793.7700', '4. close': '795.3500', '5. volume': '22345722'}, '2022-03-10': {'1. open': '851.4500', '2. high': '854.4500', '3. low': '810.3601', '4. close': '838.3000', '5. volume': '19549548'}, '2022-03-09': {'1. open': '839.4800', '2. high': '860.5600', '3. low': '832.0100', '4. close': '858.9700', '5. volume': '19727993'}, '2022-03-08': {'1. open': '795.5300', '2. high': '849.9900', '3. low': '782.1700', '4. close': '824.4000', '5. volume': '26799702'}, '2022-03-07': {'1. open': '856.3000', '2. high': '866.1400', '3. low': '804.5700', '4. close': '804.5800', '5. volume': '24164724'}, '2022-03-04': {'1. open': '849.1000', '2. high': '855.6500', '3. low': '825.1609', '4. close': '838.2900', '5. volume': '22393287'}, '2022-03-03': {'1. open': '878.7700', '2. high': '886.4390', '3. low': '832.6001', '4. close': '839.2900', '5. volume': '20541169'}, '2022-03-02': {'1. open': '872.1300', '2. high': '886.4800', '3. low': '844.2721', '4. close': '879.8900', '5. volume': '24881146'}, '2022-03-01': {'1. open': '869.6800', '2. high': '889.8800', '3. low': '853.7800', '4. close': '864.3700', '5. volume': '24922287'}, '2022-02-28': {'1. open': '815.0100', '2. high': '876.8600', '3. low': '814.7075', '4. close': '870.4300', '5. volume': '33002289'}, '2022-02-25': {'1. open': '809.2300', '2. high': '819.5000', '3. low': '782.4005', '4. close': '809.8700', '5. volume': '25355921'}, '2022-02-24': {'1. open': '700.3900', '2. high': '802.4800', '3. low': '700.0000', '4. close': '800.7700', '5. volume': '45107425'}, '2022-02-23': {'1. open': '830.4300', '2. high': '835.2997', '3. low': '760.5600', '4. close': '764.0400', '5. volume': '31752336'}, '2022-02-22': {'1. open': '834.1300', '2. high': '856.7338', '3. low': '801.1001', '4. close': '821.5300', '5. volume': '27387874'}, '2022-02-18': {'1. open': '886.0000', '2. high': '886.8700', '3. low': '837.6100', '4. close': '856.9800', '5. volume': '22833947'}, '2022-02-17': {'1. open': '913.2600', '2. high': '918.4999', '3. low': '874.1000', '4. close': '876.3500', '5. volume': '18392806'}, '2022-02-16': {'1. open': '914.0500', '2. high': '926.4299', '3. low': '901.2100', '4. close': '923.3900', '5. volume': '17098132'}, '2022-02-15': {'1. open': '900.0000', '2. high': '923.0000', '3. low': '893.3774', '4. close': '922.4300', '5. volume': '19216514'}, '2022-02-14': {'1. open': '861.5700', '2. high': '898.8799', '3. low': '853.1500', '4. close': '875.7600', '5. volume': '22585472'}, '2022-02-11': {'1. open': '909.6300', '2. high': '915.9600', '3. low': '850.7000', '4. close': '860.0000', '5. volume': '26548623'}, '2022-02-10': {'1. open': '908.3700', '2. high': '943.8100', '3. low': '896.7000', '4. close': '904.5500', '5. volume': '22042277'}, '2022-02-09': {'1. open': '935.0000', '2. high': '946.2699', '3. low': '920.0000', '4. close': '932.0000', '5. volume': '17419848'}, '2022-02-08': {'1. open': '905.5300', '2. high': '926.2899', '3. low': '894.8000', '4. close': '922.0000', '5. volume': '16909671'}, '2022-02-07': {'1. open': '923.7900', '2. high': '947.7700', '3. low': '902.7089', '4. close': '907.3400', '5. volume': '20331488'}, '2022-02-04': {'1. open': '897.2200', '2. high': '936.5000', '3. low': '881.1700', '4. close': '923.3200', '5. volume': '24541822'}, '2022-02-03': {'1. open': '882.0000', '2. high': '937.0000', '3. low': '880.5200', '4. close': '891.1400', '5. volume': '26285186'}, '2022-02-02': {'1. open': '928.1800', '2. high': '931.5000', '3. low': '889.4100', '4. close': '905.6600', '5. volume': '22264345'}, '2022-02-01': {'1. open': '935.2100', '2. high': '943.7000', '3. low': '905.0000', '4. close': '931.2500', '5. volume': '24379446'}, '2022-01-31': {'1. open': '872.7100', '2. high': '937.9900', '3. low': '862.0500', '4. close': '936.7200', '5. volume': '34812032'}, '2022-01-28': {'1. open': '831.5600', '2. high': '857.5000', '3. low': '792.0100', '4. close': '846.3500', '5. volume': '44929650'}, '2022-01-27': {'1. open': '933.3600', '2. high': '935.3900', '3. low': '829.0000', '4. close': '829.1000', '5. volume': '49036523'}, '2022-01-26': {'1. open': '952.4300', '2. high': '987.6900', '3. low': '906.0000', '4. close': '937.4100', '5. volume': '34955761'}, '2022-01-25': {'1. open': '914.2000', '2. high': '951.2600', '3. low': '903.2100', '4. close': '918.4000', '5. volume': '28865302'}, '2022-01-24': {'1. open': '904.7600', '2. high': '933.5131', '3. low': '851.4700', '4. close': '930.0000', '5. volume': '50791714'}, '2022-01-21': {'1. open': '996.3400', '2. high': '1004.5500', '3. low': '940.5000', '4. close': '943.9000', '5. volume': '34472009'}, '2022-01-20': {'1. open': '1009.7300', '2. high': '1041.6600', '3. low': '994.0000', '4. close': '996.2700', '5. volume': '23496248'}, '2022-01-19': {'1. open': '1041.7050', '2. high': '1054.6699', '3. low': '995.0000', '4. close': '995.6500', '5. volume': '24870215'}, '2022-01-18': {'1. open': '1026.6050', '2. high': '1070.7899', '3. low': '1016.0600', '4. close': '1030.5100', '5. volume': '22158412'}, '2022-01-14': {'1. open': '1019.8800', '2. high': '1052.0000', '3. low': '1013.3788', '4. close': '1049.6100', '5. volume': '24308137'}, '2022-01-13': {'1. open': '1109.0650', '2. high': '1115.6000', '3. low': '1026.5391', '4. close': '1031.5600', '5. volume': '32403264'}, '2022-01-12': {'1. open': '1078.8500', '2. high': '1114.8400', '3. low': '1072.5901', '4. close': '1106.2200', '5. volume': '27913005'}, '2022-01-11': {'1. open': '1053.6700', '2. high': '1075.8500', '3. low': '1038.8200', '4. close': '1064.4000', '5. volume': '21593308'}, '2022-01-10': {'1. open': '1000.0000', '2. high': '1059.1000', '3. low': '980.0000', '4. close': '1058.1200', '5. volume': '30604959'}, '2022-01-07': {'1. open': '1080.3700', '2. high': '1080.9299', '3. low': '1010.0000', '4. close': '1026.9600', '5. volume': '28054916'}, '2022-01-06': {'1. open': '1077.0000', '2. high': '1088.0000', '3. low': '1020.5000', '4. close': '1064.7000', '5. volume': '30112158'}, '2022-01-05': {'1. open': '1146.6500', '2. high': '1170.3400', '3. low': '1081.0101', '4. close': '1088.1200', '5. volume': '26706599'}, '2022-01-04': {'1. open': '1189.5500', '2. high': '1208.0000', '3. low': '1123.0500', '4. close': '1149.5900', '5. volume': '33416086'}, '2022-01-03': {'1. open': '1147.7500', '2. high': '1201.0700', '3. low': '1136.0400', '4. close': '1199.7800', '5. volume': '34895349'}, '2021-12-31': {'1. open': '1073.4444', '2. high': '1081.9999', '3. low': '1054.5900', '4. close': '1056.7800', '5. volume': '13466216'}, '2021-12-30': {'1. open': '1061.3300', '2. high': '1095.5500', '3. low': '1053.1500', '4. close': '1070.3400', '5. volume': '15680313'}, '2021-12-29': {'1. open': '1098.6400', '2. high': '1104.0000', '3. low': '1064.1400', '4. close': '1086.1900', '5. volume': '18718015'}, '2021-12-28': {'1. open': '1109.4900', '2. high': '1118.9999', '3. low': '1078.4200', '4. close': '1088.4700', '5. volume': '20107969'}, '2021-12-27': {'1. open': '1073.6700', '2. high': '1117.0000', '3. low': '1070.7152', '4. close': '1093.9400', '5. volume': '23715273'}, '2021-12-23': {'1. open': '1006.8000', '2. high': '1072.9767', '3. low': '997.5600', '4. close': '1067.0000', '5. volume': '30904429'}, '2021-12-22': {'1. open': '965.6600', '2. high': '1015.6599', '3. low': '957.0500', '4. close': '1008.8700', '5. volume': '31211362'}, '2021-12-21': {'1. open': '916.8700', '2. high': '939.5000', '3. low': '886.1200', '4. close': '938.5300', '5. volume': '23839305'}, '2021-12-20': {'1. open': '910.7000', '2. high': '921.6884', '3. low': '893.3900', '4. close': '899.9400', '5. volume': '18826671'}, '2021-12-17': {'1. open': '914.7700', '2. high': '960.6599', '3. low': '909.0401', '4. close': '932.5700', '5. volume': '33626754'}, '2021-12-16': {'1. open': '994.5000', '2. high': '994.9800', '3. low': '921.8500', '4. close': '926.9200', '5. volume': '27590483'}, '2021-12-15': {'1. open': '953.2100', '2. high': '978.7499', '3. low': '928.2501', '4. close': '975.9900', '5. volume': '25056410'}, '2021-12-14': {'1. open': '945.0000', '2. high': '966.4100', '3. low': '930.0000', '4. close': '958.5100', '5. volume': '23602090'}, '2021-12-13': {'1. open': '1001.0900', '2. high': '1005.0000', '3. low': '951.4200', '4. close': '966.4100', '5. volume': '26198502'}, '2021-12-10': {'1. open': '1008.7500', '2. high': '1020.9797', '3. low': '982.5300', '4. close': '1017.0300', '5. volume': '19888122'}, '2021-12-09': {'1. open': '1060.6400', '2. high': '1062.4900', '3. low': '1002.3600', '4. close': '1003.8000', '5. volume': '19812832'}, '2021-12-08': {'1. open': '1052.7100', '2. high': '1072.3800', '3. low': '1033.0001', '4. close': '1068.9600', '5. volume': '13968790'}, '2021-12-07': {'1. open': '1044.2000', '2. high': '1057.6739', '3. low': '1026.8100', '4. close': '1051.7500', '5. volume': '18694857'}, '2021-12-06': {'1. open': '1001.5100', '2. high': '1021.6400', '3. low': '950.5000', '4. close': '1009.0100', '5. volume': '27221037'}, '2021-12-03': {'1. open': '1084.7900', '2. high': '1090.5753', '3. low': '1000.2100', '4. close': '1014.9700', '5. volume': '30773995'}, '2021-12-02': {'1. open': '1099.0600', '2. high': '1113.0000', '3. low': '1056.6500', '4. close': '1084.6000', '5. volume': '24371623'}, '2021-12-01': {'1. open': '1160.6950', '2. high': '1172.8399', '3. low': '1090.7600', '4. close': '1095.0000', '5. volume': '22934698'}}}

In [6]:
import pandas as pd
import requests

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=TD&datatype=json&apikey=DRDU0ACD89IZ5H2D'
r_stock_price = requests.get(url)
data_stock_price = r_stock_price.json()

print(data_stock_price)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'TD', '3. Last Refreshed': '2022-04-25', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2022-04-25': {'1. open': '72.7100', '2. high': '73.4200', '3. low': '71.5100', '4. close': '73.1300', '5. volume': '2538138'}, '2022-04-22': {'1. open': '75.0000', '2. high': '75.0000', '3. low': '73.1200', '4. close': '73.3200', '5. volume': '2316120'}, '2022-04-21': {'1. open': '76.5900', '2. high': '77.4500', '3. low': '75.0450', '4. close': '75.2500', '5. volume': '1666796'}, '2022-04-20': {'1. open': '75.7100', '2. high': '76.6600', '3. low': '75.5200', '4. close': '76.1500', '5. volume': '1644099'}, '2022-04-19': {'1. open': '74.4500', '2. high': '75.0000', '3. low': '74.1800', '4. close': '74.8800', '5. volume': '1792038'}, '2022-04-18': {'1. open': '74.3800', '2. high': '74.7750', '3. low': '74.0200', '4. close': '74.2400', '5. volume': '1257389'}, '2022-04-14': {'1. open': '74.6100', '2. high': '75.0800', '3. low': '74.4400', '4. close': '74.5000', '5. volume': '2136664'}, '2022-04-13': {'1. open': '74.2500', '2. high': '74.9550', '3. low': '73.7000', '4. close': '74.6900', '5. volume': '2201571'}, '2022-04-12': {'1. open': '76.9700', '2. high': '77.0200', '3. low': '74.7400', '4. close': '74.8500', '5. volume': '2223332'}, '2022-04-11': {'1. open': '76.5400', '2. high': '77.4800', '3. low': '76.3200', '4. close': '76.5100', '5. volume': '1933169'}, '2022-04-08': {'1. open': '76.6200', '2. high': '77.7400', '3. low': '76.5300', '4. close': '76.9600', '5. volume': '1431489'}, '2022-04-07': {'1. open': '77.9400', '2. high': '78.2200', '3. low': '75.9200', '4. close': '76.6200', '5. volume': '4313810'}, '2022-04-06': {'1. open': '79.9200', '2. high': '79.9300', '3. low': '78.6900', '4. close': '79.1200', '5. volume': '3458871'}, '2022-04-05': {'1. open': '80.8200', '2. high': '81.4700', '3. low': '80.1000', '4. close': '80.2200', '5. volume': '1850460'}, '2022-04-04': {'1. open': '79.6900', '2. high': '80.5300', '3. low': '79.2700', '4. close': '80.4800', '5. volume': '2551904'}, '2022-04-01': {'1. open': '80.0400', '2. high': '80.2600', '3. low': '78.8100', '4. close': '79.5000', '5. volume': '1681157'}, '2022-03-31': {'1. open': '80.6700', '2. high': '81.2800', '3. low': '79.1800', '4. close': '79.4200', '5. volume': '2150656'}, '2022-03-30': {'1. open': '81.4700', '2. high': '81.7600', '3. low': '80.5450', '4. close': '81.2700', '5. volume': '1634597'}, '2022-03-29': {'1. open': '82.2300', '2. high': '82.3800', '3. low': '80.9400', '4. close': '81.2700', '5. volume': '1428750'}, '2022-03-28': {'1. open': '81.2700', '2. high': '81.5000', '3. low': '80.6000', '4. close': '81.4700', '5. volume': '1687615'}, '2022-03-25': {'1. open': '80.9300', '2. high': '81.7450', '3. low': '80.5700', '4. close': '81.7100', '5. volume': '1488465'}, '2022-03-24': {'1. open': '80.8200', '2. high': '81.0400', '3. low': '80.1650', '4. close': '80.5900', '5. volume': '1641976'}, '2022-03-23': {'1. open': '81.4100', '2. high': '81.5200', '3. low': '80.2300', '4. close': '80.4200', '5. volume': '1951261'}, '2022-03-22': {'1. open': '82.0500', '2. high': '82.6400', '3. low': '81.8100', '4. close': '81.8900', '5. volume': '2667982'}, '2022-03-21': {'1. open': '81.1500', '2. high': '81.8400', '3. low': '81.0000', '4. close': '81.6600', '5. volume': '1822399'}, '2022-03-18': {'1. open': '80.6400', '2. high': '81.3000', '3. low': '80.0700', '4. close': '80.9200', '5. volume': '1818516'}, '2022-03-17': {'1. open': '79.5000', '2. high': '80.9900', '3. low': '79.5000', '4. close': '80.9700', '5. volume': '1768353'}, '2022-03-16': {'1. open': '79.2500', '2. high': '80.1300', '3. low': '78.0900', '4. close': '79.7000', '5. volume': '2228785'}, '2022-03-15': {'1. open': '77.5000', '2. high': '78.3600', '3. low': '76.3500', '4. close': '78.2600', '5. volume': '1782655'}, '2022-03-14': {'1. open': '77.6100', '2. high': '78.4400', '3. low': '76.8800', '4. close': '77.1900', '5. volume': '3083104'}, '2022-03-11': {'1. open': '77.4200', '2. high': '78.1800', '3. low': '76.9050', '4. close': '76.9600', '5. volume': '1526017'}, '2022-03-10': {'1. open': '76.3400', '2. high': '77.3750', '3. low': '75.9250', '4. close': '76.9600', '5. volume': '1649735'}, '2022-03-09': {'1. open': '76.6700', '2. high': '77.4000', '3. low': '76.1900', '4. close': '76.8500', '5. volume': '2231365'}, '2022-03-08': {'1. open': '76.0700', '2. high': '76.5500', '3. low': '74.2100', '4. close': '74.6900', '5. volume': '3120083'}, '2022-03-07': {'1. open': '76.3500', '2. high': '76.9100', '3. low': '75.6100', '4. close': '75.8300', '5. volume': '3101513'}, '2022-03-04': {'1. open': '76.5600', '2. high': '77.7500', '3. low': '75.9300', '4. close': '77.4500', '5. volume': '2505044'}, '2022-03-03': {'1. open': '79.2100', '2. high': '80.0100', '3. low': '77.3200', '4. close': '77.4900', '5. volume': '2335980'}, '2022-03-02': {'1. open': '78.0600', '2. high': '80.4300', '3. low': '78.0600', '4. close': '80.3200', '5. volume': '2651306'}, '2022-03-01': {'1. open': '80.4900', '2. high': '80.7800', '3. low': '77.2300', '4. close': '77.6000', '5. volume': '3207821'}, '2022-02-28': {'1. open': '81.2000', '2. high': '81.7100', '3. low': '80.0250', '4. close': '80.6900', '5. volume': '3936141'}, '2022-02-25': {'1. open': '80.5900', '2. high': '82.6150', '3. low': '80.4300', '4. close': '82.4300', '5. volume': '2023387'}, '2022-02-24': {'1. open': '78.5700', '2. high': '80.0308', '3. low': '78.1400', '4. close': '79.9200', '5. volume': '3845947'}, '2022-02-23': {'1. open': '83.5450', '2. high': '83.7700', '3. low': '81.7700', '4. close': '82.0800', '5. volume': '2527599'}, '2022-02-22': {'1. open': '82.7100', '2. high': '83.3600', '3. low': '81.9400', '4. close': '83.0900', '5. volume': '2473256'}, '2022-02-18': {'1. open': '83.9000', '2. high': '84.0800', '3. low': '83.1700', '4. close': '83.2200', '5. volume': '2022914'}, '2022-02-17': {'1. open': '84.5400', '2. high': '84.8300', '3. low': '83.7600', '4. close': '83.9000', '5. volume': '2268824'}, '2022-02-16': {'1. open': '83.8800', '2. high': '85.3900', '3. low': '83.6900', '4. close': '85.0000', '5. volume': '1393287'}, '2022-02-15': {'1. open': '84.0200', '2. high': '84.2900', '3. low': '83.5200', '4. close': '83.9500', '5. volume': '2353353'}, '2022-02-14': {'1. open': '84.1300', '2. high': '84.4600', '3. low': '82.9250', '4. close': '83.4300', '5. volume': '2540297'}, '2022-02-11': {'1. open': '84.6000', '2. high': '86.0150', '3. low': '84.1700', '4. close': '84.5800', '5. volume': '2316849'}, '2022-02-10': {'1. open': '84.1800', '2. high': '85.6100', '3. low': '84.1700', '4. close': '84.7800', '5. volume': '2264628'}, '2022-02-09': {'1. open': '84.9600', '2. high': '85.4300', '3. low': '84.4400', '4. close': '84.6500', '5. volume': '2471414'}, '2022-02-08': {'1. open': '83.8600', '2. high': '84.8150', '3. low': '83.7800', '4. close': '84.6300', '5. volume': '1986683'}, '2022-02-07': {'1. open': '83.2900', '2. high': '83.9500', '3. low': '83.0300', '4. close': '83.7700', '5. volume': '1654763'}, '2022-02-04': {'1. open': '82.6200', '2. high': '83.3200', '3. low': '82.3050', '4. close': '82.7900', '5. volume': '1801260'}, '2022-02-03': {'1. open': '82.4800', '2. high': '83.7700', '3. low': '82.2600', '4. close': '82.8900', '5. volume': '2383609'}, '2022-02-02': {'1. open': '82.0400', '2. high': '83.2300', '3. low': '81.8500', '4. close': '83.0500', '5. volume': '1826284'}, '2022-02-01': {'1. open': '80.0100', '2. high': '81.6300', '3. low': '79.8700', '4. close': '81.5400', '5. volume': '2432542'}, '2022-01-31': {'1. open': '78.3800', '2. high': '80.1001', '3. low': '78.0100', '4. close': '80.0300', '5. volume': '1528404'}, '2022-01-28': {'1. open': '78.9200', '2. high': '78.9500', '3. low': '77.4900', '4. close': '78.4500', '5. volume': '1781811'}, '2022-01-27': {'1. open': '79.6600', '2. high': '80.2700', '3. low': '78.5700', '4. close': '78.9500', '5. volume': '2156294'}, '2022-01-26': {'1. open': '80.1700', '2. high': '80.4500', '3. low': '78.4900', '4. close': '79.0500', '5. volume': '3187760'}, '2022-01-25': {'1. open': '77.9000', '2. high': '79.7400', '3. low': '77.1200', '4. close': '79.1300', '5. volume': '2053377'}, '2022-01-24': {'1. open': '78.0100', '2. high': '78.5100', '3. low': '76.3100', '4. close': '78.4200', '5. volume': '3083791'}, '2022-01-21': {'1. open': '80.7100', '2. high': '81.0500', '3. low': '79.3300', '4. close': '79.6900', '5. volume': '2210531'}, '2022-01-20': {'1. open': '81.2300', '2. high': '82.5100', '3. low': '81.0400', '4. close': '81.3100', '5. volume': '1655516'}, '2022-01-19': {'1. open': '82.7300', '2. high': '82.8800', '3. low': '81.0100', '4. close': '81.2500', '5. volume': '2859865'}, '2022-01-18': {'1. open': '82.6300', '2. high': '83.0800', '3. low': '82.1550', '4. close': '82.5200', '5. volume': '1888003'}, '2022-01-14': {'1. open': '80.7500', '2. high': '82.1000', '3. low': '80.4700', '4. close': '81.6400', '5. volume': '1878039'}, '2022-01-13': {'1. open': '81.5500', '2. high': '82.3800', '3. low': '81.2300', '4. close': '81.3700', '5. volume': '1546683'}, '2022-01-12': {'1. open': '80.1600', '2. high': '81.1400', '3. low': '80.1500', '4. close': '81.1400', '5. volume': '2563947'}, '2022-01-11': {'1. open': '78.7900', '2. high': '80.1250', '3. low': '78.7900', '4. close': '80.1100', '5. volume': '1651930'}, '2022-01-10': {'1. open': '79.1300', '2. high': '79.2900', '3. low': '78.2000', '4. close': '78.6900', '5. volume': '1884558'}, '2022-01-07': {'1. open': '78.7300', '2. high': '79.4200', '3. low': '78.2750', '4. close': '79.2100', '5. volume': '3396732'}, '2022-01-06': {'1. open': '78.9900', '2. high': '79.3600', '3. low': '78.6100', '4. close': '79.0700', '5. volume': '3486288'}, '2022-01-05': {'1. open': '78.6300', '2. high': '79.5500', '3. low': '78.2600', '4. close': '78.3000', '5. volume': '1652147'}, '2022-01-04': {'1. open': '77.8900', '2. high': '78.7100', '3. low': '77.4900', '4. close': '78.2100', '5. volume': '2043194'}, '2022-01-03': {'1. open': '76.9300', '2. high': '77.8700', '3. low': '76.9300', '4. close': '77.7600', '5. volume': '1490142'}, '2021-12-31': {'1. open': '76.5300', '2. high': '76.8900', '3. low': '76.2700', '4. close': '76.6800', '5. volume': '937241'}, '2021-12-30': {'1. open': '76.2700', '2. high': '76.6300', '3. low': '76.0900', '4. close': '76.3000', '5. volume': '841164'}, '2021-12-29': {'1. open': '76.2400', '2. high': '76.6500', '3. low': '76.0500', '4. close': '76.1900', '5. volume': '1256191'}, '2021-12-28': {'1. open': '76.3700', '2. high': '77.2000', '3. low': '76.3700', '4. close': '76.5000', '5. volume': '964867'}, '2021-12-27': {'1. open': '75.2800', '2. high': '76.5800', '3. low': '75.1600', '4. close': '76.4700', '5. volume': '845378'}, '2021-12-23': {'1. open': '74.7100', '2. high': '75.2500', '3. low': '74.6000', '4. close': '75.1300', '5. volume': '1026264'}, '2021-12-22': {'1. open': '73.2500', '2. high': '74.3600', '3. low': '73.2500', '4. close': '74.3500', '5. volume': '1169767'}, '2021-12-21': {'1. open': '73.4300', '2. high': '73.4700', '3. low': '73.0000', '4. close': '73.3600', '5. volume': '1426818'}, '2021-12-20': {'1. open': '72.3900', '2. high': '72.8300', '3. low': '71.8900', '4. close': '72.6100', '5. volume': '1906329'}, '2021-12-17': {'1. open': '73.5900', '2. high': '74.1600', '3. low': '72.9100', '4. close': '73.0100', '5. volume': '2145903'}, '2021-12-16': {'1. open': '74.7800', '2. high': '75.6800', '3. low': '74.5300', '4. close': '74.7600', '5. volume': '1660303'}, '2021-12-15': {'1. open': '73.7300', '2. high': '74.3800', '3. low': '73.3800', '4. close': '74.1600', '5. volume': '5949160'}, '2021-12-14': {'1. open': '73.8800', '2. high': '74.7200', '3. low': '73.5800', '4. close': '73.7000', '5. volume': '1433373'}, '2021-12-13': {'1. open': '74.6600', '2. high': '74.7800', '3. low': '73.8850', '4. close': '74.1100', '5. volume': '1821832'}, '2021-12-10': {'1. open': '75.2800', '2. high': '75.4500', '3. low': '74.8050', '4. close': '74.9500', '5. volume': '1347284'}, '2021-12-09': {'1. open': '74.8300', '2. high': '75.3000', '3. low': '74.7200', '4. close': '75.0500', '5. volume': '991618'}, '2021-12-08': {'1. open': '75.3700', '2. high': '75.6200', '3. low': '74.9800', '4. close': '75.4900', '5. volume': '1522361'}, '2021-12-07': {'1. open': '74.5300', '2. high': '75.3050', '3. low': '74.5300', '4. close': '75.0400', '5. volume': '1641261'}, '2021-12-06': {'1. open': '75.1600', '2. high': '75.2700', '3. low': '73.9700', '4. close': '74.0200', '5. volume': '1775005'}, '2021-12-03': {'1. open': '75.4600', '2. high': '75.4600', '3. low': '74.2000', '4. close': '74.4300', '5. volume': '2001085'}, '2021-12-02': {'1. open': '72.9900', '2. high': '75.5300', '3. low': '72.8600', '4. close': '75.3200', '5. volume': '2558192'}, '2021-12-01': {'1. open': '72.4400', '2. high': '73.5500', '3. low': '71.6750', '4. close': '71.7300', '5. volume': '3304148'}}}

In [7]:
import pandas as pd
import requests

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AC&datatype=json&apikey=DRDU0ACD89IZ5H2D'
r_stock_price = requests.get(url)
data_stock_price = r_stock_price.json()

print(data_stock_price)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'AC', '3. Last Refreshed': '2022-04-25', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2022-04-25': {'1. open': '39.4100', '2. high': '40.2126', '3. low': '38.2000', '4. close': '39.5000', '5. volume': '7149'}, '2022-04-22': {'1. open': '39.9100', '2. high': '40.5050', '3. low': '39.7600', '4. close': '39.7600', '5. volume': '5559'}, '2022-04-21': {'1. open': '39.5000', '2. high': '40.7500', '3. low': '39.5000', '4. close': '39.9000', '5. volume': '8253'}, '2022-04-20': {'1. open': '38.9600', '2. high': '41.0182', '3. low': '38.9600', '4. close': '39.8300', '5. volume': '10025'}, '2022-04-19': {'1. open': '36.9968', '2. high': '39.8600', '3. low': '36.9968', '4. close': '38.9600', '5. volume': '27662'}, '2022-04-18': {'1. open': '38.2000', '2. high': '40.1000', '3. low': '37.8900', '4. close': '38.2000', '5. volume': '22241'}, '2022-04-14': {'1. open': '38.4500', '2. high': '39.5412', '3. low': '38.4500', '4. close': '38.5700', '5. volume': '1596'}, '2022-04-13': {'1. open': '38.2500', '2. high': '39.6390', '3. low': '38.0700', '4. close': '38.0700', '5. volume': '22307'}, '2022-04-12': {'1. open': '37.3400', '2. high': '39.0800', '3. low': '36.8859', '4. close': '37.8900', '5. volume': '22021'}, '2022-04-11': {'1. open': '37.7500', '2. high': '38.3100', '3. low': '36.5800', '4. close': '37.2100', '5. volume': '4416'}, '2022-04-08': {'1. open': '37.8997', '2. high': '38.2700', '3. low': '37.5100', '4. close': '37.5600', '5. volume': '3539'}, '2022-04-07': {'1. open': '38.5000', '2. high': '39.6950', '3. low': '38.3500', '4. close': '39.0100', '5. volume': '8660'}, '2022-04-06': {'1. open': '38.0300', '2. high': '39.5000', '3. low': '36.9700', '4. close': '38.4200', '5. volume': '23772'}, '2022-04-05': {'1. open': '39.6100', '2. high': '39.9172', '3. low': '38.3000', '4. close': '38.7200', '5. volume': '2902'}, '2022-04-04': {'1. open': '40.8220', '2. high': '40.8220', '3. low': '39.2100', '4. close': '39.2100', '5. volume': '5882'}, '2022-04-01': {'1. open': '41.5900', '2. high': '41.5900', '3. low': '40.5000', '4. close': '40.9700', '5. volume': '11592'}, '2022-03-31': {'1. open': '43.0964', '2. high': '43.0964', '3. low': '41.3100', '4. close': '41.9100', '5. volume': '3389'}, '2022-03-30': {'1. open': '41.5000', '2. high': '41.6500', '3. low': '41.0100', '4. close': '41.0100', '5. volume': '1805'}, '2022-03-29': {'1. open': '41.1200', '2. high': '42.1750', '3. low': '40.8500', '4. close': '41.9100', '5. volume': '4265'}, '2022-03-28': {'1. open': '41.3500', '2. high': '41.3500', '3. low': '40.7424', '4. close': '41.0100', '5. volume': '5834'}, '2022-03-25': {'1. open': '41.0000', '2. high': '41.4894', '3. low': '40.9600', '4. close': '41.3500', '5. volume': '6321'}, '2022-03-24': {'1. open': '40.6500', '2. high': '41.0000', '3. low': '40.6500', '4. close': '41.0000', '5. volume': '2322'}, '2022-03-23': {'1. open': '40.4000', '2. high': '41.2100', '3. low': '39.9700', '4. close': '40.6500', '5. volume': '7929'}, '2022-03-22': {'1. open': '40.2100', '2. high': '40.5800', '3. low': '40.1000', '4. close': '40.5800', '5. volume': '3354'}, '2022-03-21': {'1. open': '41.1000', '2. high': '41.1000', '3. low': '39.6000', '4. close': '40.3000', '5. volume': '7155'}, '2022-03-18': {'1. open': '40.6500', '2. high': '41.5000', '3. low': '40.6500', '4. close': '41.4400', '5. volume': '10485'}, '2022-03-17': {'1. open': '41.1000', '2. high': '41.9500', '3. low': '40.9950', '4. close': '41.2000', '5. volume': '9106'}, '2022-03-16': {'1. open': '42.0100', '2. high': '42.0100', '3. low': '40.0300', '4. close': '41.0800', '5. volume': '17942'}, '2022-03-15': {'1. open': '39.5000', '2. high': '42.5500', '3. low': '39.5000', '4. close': '40.9000', '5. volume': '38602'}, '2022-03-14': {'1. open': '40.4500', '2. high': '41.5250', '3. low': '39.4100', '4. close': '40.2300', '5. volume': '8747'}, '2022-03-11': {'1. open': '40.2200', '2. high': '40.5900', '3. low': '39.8500', '4. close': '39.9700', '5. volume': '3673'}, '2022-03-10': {'1. open': '40.9400', '2. high': '42.9000', '3. low': '39.6300', '4. close': '40.1000', '5. volume': '16205'}, '2022-03-09': {'1. open': '40.0000', '2. high': '43.0000', '3. low': '40.0000', '4. close': '41.6500', '5. volume': '21017'}, '2022-03-08': {'1. open': '39.3500', '2. high': '40.3800', '3. low': '37.4500', '4. close': '39.8700', '5. volume': '30986'}, '2022-03-07': {'1. open': '40.3700', '2. high': '41.7500', '3. low': '37.8000', '4. close': '37.8000', '5. volume': '20994'}, '2022-03-04': {'1. open': '41.0000', '2. high': '41.0000', '3. low': '38.8500', '4. close': '40.5000', '5. volume': '44258'}, '2022-03-03': {'1. open': '39.9999', '2. high': '42.2000', '3. low': '39.8800', '4. close': '40.6200', '5. volume': '17033'}, '2022-03-02': {'1. open': '40.2900', '2. high': '41.6199', '3. low': '39.8600', '4. close': '40.3400', '5. volume': '7882'}, '2022-03-01': {'1. open': '39.5900', '2. high': '40.8100', '3. low': '39.5000', '4. close': '39.5000', '5. volume': '4741'}, '2022-02-28': {'1. open': '40.1200', '2. high': '40.2900', '3. low': '39.1300', '4. close': '39.1300', '5. volume': '2824'}, '2022-02-25': {'1. open': '39.1500', '2. high': '41.0850', '3. low': '39.1500', '4. close': '40.5000', '5. volume': '1914'}, '2022-02-24': {'1. open': '36.5200', '2. high': '39.4800', '3. low': '36.5000', '4. close': '38.6800', '5. volume': '13939'}, '2022-02-23': {'1. open': '38.1700', '2. high': '39.0900', '3. low': '38.1700', '4. close': '38.5200', '5. volume': '13256'}, '2022-02-22': {'1. open': '37.5200', '2. high': '38.9100', '3. low': '37.5200', '4. close': '37.9100', '5. volume': '3646'}, '2022-02-18': {'1. open': '37.8500', '2. high': '38.9210', '3. low': '37.0300', '4. close': '37.0300', '5. volume': '3000'}, '2022-02-17': {'1. open': '37.6500', '2. high': '39.0880', '3. low': '37.6500', '4. close': '37.9400', '5. volume': '10485'}, '2022-02-16': {'1. open': '39.0600', '2. high': '39.0600', '3. low': '37.9000', '4. close': '37.9000', '5. volume': '8455'}, '2022-02-15': {'1. open': '38.0900', '2. high': '39.4061', '3. low': '38.0500', '4. close': '38.5000', '5. volume': '3456'}, '2022-02-14': {'1. open': '37.4800', '2. high': '39.7200', '3. low': '37.4800', '4. close': '37.6700', '5. volume': '14236'}, '2022-02-11': {'1. open': '38.4000', '2. high': '38.8500', '3. low': '37.5100', '4. close': '37.5100', '5. volume': '3126'}, '2022-02-10': {'1. open': '40.2000', '2. high': '40.4495', '3. low': '37.8300', '4. close': '38.0400', '5. volume': '11225'}, '2022-02-09': {'1. open': '42.1800', '2. high': '42.2000', '3. low': '40.3000', '4. close': '41.0000', '5. volume': '11423'}, '2022-02-08': {'1. open': '45.5100', '2. high': '45.5100', '3. low': '41.4650', '4. close': '41.7000', '5. volume': '29727'}, '2022-02-07': {'1. open': '40.6500', '2. high': '44.5000', '3. low': '39.9500', '4. close': '41.5000', '5. volume': '43173'}, '2022-02-04': {'1. open': '40.7000', '2. high': '43.3000', '3. low': '40.7000', '4. close': '40.9500', '5. volume': '8468'}, '2022-02-03': {'1. open': '41.6100', '2. high': '41.6100', '3. low': '39.9400', '4. close': '39.9400', '5. volume': '2070'}, '2022-02-02': {'1. open': '43.0000', '2. high': '43.0000', '3. low': '41.7387', '4. close': '41.9200', '5. volume': '3115'}, '2022-02-01': {'1. open': '45.0000', '2. high': '45.4600', '3. low': '42.0950', '4. close': '42.7700', '5. volume': '10328'}, '2022-01-31': {'1. open': '45.6000', '2. high': '46.7000', '3. low': '44.8500', '4. close': '44.9000', '5. volume': '3951'}, '2022-01-28': {'1. open': '47.0000', '2. high': '47.0000', '3. low': '44.9500', '4. close': '45.8400', '5. volume': '3026'}, '2022-01-27': {'1. open': '45.4300', '2. high': '47.5000', '3. low': '44.9500', '4. close': '45.4900', '5. volume': '1746'}, '2022-01-26': {'1. open': '46.3500', '2. high': '46.3500', '3. low': '44.9200', '4. close': '44.9200', '5. volume': '2602'}, '2022-01-25': {'1. open': '44.2200', '2. high': '46.3500', '3. low': '44.2200', '4. close': '46.3500', '5. volume': '2481'}, '2022-01-24': {'1. open': '42.6100', '2. high': '44.0700', '3. low': '42.5900', '4. close': '44.0700', '5. volume': '4709'}, '2022-01-21': {'1. open': '42.9100', '2. high': '43.2000', '3. low': '42.0614', '4. close': '42.1700', '5. volume': '5775'}, '2022-01-20': {'1. open': '44.9699', '2. high': '44.9699', '3. low': '43.0000', '4. close': '43.2500', '5. volume': '18511'}, '2022-01-19': {'1. open': '43.9400', '2. high': '44.1299', '3. low': '43.3900', '4. close': '43.3900', '5. volume': '1328'}, '2022-01-18': {'1. open': '45.9400', '2. high': '45.9500', '3. low': '43.5100', '4. close': '43.5100', '5. volume': '7057'}, '2022-01-14': {'1. open': '46.6000', '2. high': '46.6000', '3. low': '44.6684', '4. close': '45.8000', '5. volume': '2397'}, '2022-01-13': {'1. open': '45.0000', '2. high': '46.1600', '3. low': '45.0000', '4. close': '45.0900', '5. volume': '2074'}, '2022-01-12': {'1. open': '45.3700', '2. high': '46.2000', '3. low': '44.7000', '4. close': '44.7200', '5. volume': '5533'}, '2022-01-11': {'1. open': '43.5000', '2. high': '45.5300', '3. low': '43.2479', '4. close': '45.5300', '5. volume': '3557'}, '2022-01-10': {'1. open': '43.0000', '2. high': '43.5000', '3. low': '42.6100', '4. close': '43.5000', '5. volume': '5843'}, '2022-01-07': {'1. open': '43.4000', '2. high': '43.4600', '3. low': '42.4400', '4. close': '42.4400', '5. volume': '3000'}, '2022-01-06': {'1. open': '43.5000', '2. high': '44.1600', '3. low': '42.8650', '4. close': '44.1600', '5. volume': '4227'}, '2022-01-05': {'1. open': '44.3000', '2. high': '44.3000', '3. low': '42.9549', '4. close': '43.6200', '5. volume': '1902'}, '2022-01-04': {'1. open': '44.4000', '2. high': '44.8500', '3. low': '43.6500', '4. close': '44.4100', '5. volume': '3994'}, '2022-01-03': {'1. open': '43.6000', '2. high': '44.3200', '3. low': '43.3400', '4. close': '43.7600', '5. volume': '5739'}, '2021-12-31': {'1. open': '43.5500', '2. high': '43.7000', '3. low': '42.0700', '4. close': '43.0000', '5. volume': '5575'}, '2021-12-30': {'1. open': '44.6500', '2. high': '44.6600', '3. low': '43.7400', '4. close': '43.7400', '5. volume': '1555'}, '2021-12-29': {'1. open': '45.2200', '2. high': '45.2200', '3. low': '43.9900', '4. close': '44.6000', '5. volume': '5414'}, '2021-12-28': {'1. open': '45.5000', '2. high': '45.6000', '3. low': '44.6400', '4. close': '44.6400', '5. volume': '2363'}, '2021-12-27': {'1. open': '44.5000', '2. high': '46.0900', '3. low': '43.8700', '4. close': '45.5000', '5. volume': '14740'}, '2021-12-23': {'1. open': '44.1900', '2. high': '44.9500', '3. low': '44.0100', '4. close': '44.9500', '5. volume': '2249'}, '2021-12-22': {'1. open': '44.5000', '2. high': '44.5000', '3. low': '44.5000', '4. close': '44.5000', '5. volume': '940'}, '2021-12-21': {'1. open': '42.6100', '2. high': '43.9000', '3. low': '42.6100', '4. close': '43.9000', '5. volume': '5544'}, '2021-12-20': {'1. open': '43.0400', '2. high': '43.0810', '3. low': '41.8879', '4. close': '43.0000', '5. volume': '3720'}, '2021-12-17': {'1. open': '42.1500', '2. high': '44.1400', '3. low': '41.0100', '4. close': '44.1400', '5. volume': '7290'}, '2021-12-16': {'1. open': '42.5000', '2. high': '42.5700', '3. low': '41.3201', '4. close': '42.5700', '5. volume': '6098'}, '2021-12-15': {'1. open': '40.2500', '2. high': '43.0150', '3. low': '39.3900', '4. close': '42.5000', '5. volume': '5164'}, '2021-12-14': {'1. open': '39.9700', '2. high': '41.1200', '3. low': '38.5200', '4. close': '41.1200', '5. volume': '7071'}, '2021-12-13': {'1. open': '38.0100', '2. high': '39.8000', '3. low': '38.0100', '4. close': '39.4600', '5. volume': '4248'}, '2021-12-10': {'1. open': '39.9400', '2. high': '39.9900', '3. low': '38.1900', '4. close': '39.0000', '5. volume': '3711'}, '2021-12-09': {'1. open': '38.7200', '2. high': '39.3500', '3. low': '37.5100', '4. close': '37.5100', '5. volume': '2637'}, '2021-12-08': {'1. open': '37.5200', '2. high': '40.0600', '3. low': '37.3850', '4. close': '39.5000', '5. volume': '3221'}, '2021-12-07': {'1. open': '37.6300', '2. high': '38.6400', '3. low': '37.5000', '4. close': '37.5000', '5. volume': '1144'}, '2021-12-06': {'1. open': '36.5000', '2. high': '38.5900', '3. low': '36.5000', '4. close': '38.3900', '5. volume': '4676'}, '2021-12-03': {'1. open': '38.8000', '2. high': '39.6300', '3. low': '36.0700', '4. close': '36.0700', '5. volume': '12526'}, '2021-12-02': {'1. open': '39.6000', '2. high': '41.3608', '3. low': '38.7700', '4. close': '38.7700', '5. volume': '6045'}, '2021-12-01': {'1. open': '43.1433', '2. high': '43.1433', '3. low': '39.4100', '4. close': '39.6000', '5. volume': '8639'}}}

In [8]:
import pandas as pd
import requests

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=REMAX&datatype=json&apikey=DRDU0ACD89IZ5H2D'
r_stock_price = requests.get(url)
data_stock_price = r_stock_price.json()

print(data_stock_price)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'REMAX', '3. Last Refreshed': '2022-04-22', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2022-04-22': {'1. open': '16.3700', '2. high': '16.3700', '3. low': '16.3700', '4. close': '16.3700', '5. volume': '0'}, '2022-04-21': {'1. open': '16.5300', '2. high': '16.5300', '3. low': '16.5300', '4. close': '16.5300', '5. volume': '0'}, '2022-04-20': {'1. open': '16.8000', '2. high': '16.8000', '3. low': '16.8000', '4. close': '16.8000', '5. volume': '0'}, '2022-04-19': {'1. open': '16.9100', '2. high': '16.9100', '3. low': '16.9100', '4. close': '16.9100', '5. volume': '0'}, '2022-04-18': {'1. open': '16.9400', '2. high': '16.9400', '3. low': '16.9400', '4. close': '16.9400', '5. volume': '0'}, '2022-04-14': {'1. open': '17.0200', '2. high': '17.0200', '3. low': '17.0200', '4. close': '17.0200', '5. volume': '0'}, '2022-04-13': {'1. open': '17.1300', '2. high': '17.1300', '3. low': '17.1300', '4. close': '17.1300', '5. volume': '0'}, '2022-04-12': {'1. open': '16.8700', '2. high': '16.8700', '3. low': '16.8700', '4. close': '16.8700', '5. volume': '0'}, '2022-04-11': {'1. open': '16.9100', '2. high': '16.9100', '3. low': '16.9100', '4. close': '16.9100', '5. volume': '0'}, '2022-04-08': {'1. open': '17.1900', '2. high': '17.1900', '3. low': '17.1900', '4. close': '17.1900', '5. volume': '0'}, '2022-04-07': {'1. open': '17.1800', '2. high': '17.1800', '3. low': '17.1800', '4. close': '17.1800', '5. volume': '0'}, '2022-04-06': {'1. open': '17.3300', '2. high': '17.3300', '3. low': '17.3300', '4. close': '17.3300', '5. volume': '0'}, '2022-04-05': {'1. open': '17.5100', '2. high': '17.5100', '3. low': '17.5100', '4. close': '17.5100', '5. volume': '0'}, '2022-04-04': {'1. open': '17.7800', '2. high': '17.7800', '3. low': '17.7800', '4. close': '17.7800', '5. volume': '0'}, '2022-04-01': {'1. open': '17.5300', '2. high': '17.5300', '3. low': '17.5300', '4. close': '17.5300', '5. volume': '0'}, '2022-03-31': {'1. open': '17.3200', '2. high': '17.3200', '3. low': '17.3200', '4. close': '17.3200', '5. volume': '0'}, '2022-03-30': {'1. open': '17.5000', '2. high': '17.5000', '3. low': '17.5000', '4. close': '17.5000', '5. volume': '0'}, '2022-03-29': {'1. open': '17.4400', '2. high': '17.4400', '3. low': '17.4400', '4. close': '17.4400', '5. volume': '0'}, '2022-03-28': {'1. open': '17.2600', '2. high': '17.2600', '3. low': '17.2600', '4. close': '17.2600', '5. volume': '0'}, '2022-03-25': {'1. open': '17.2300', '2. high': '17.2300', '3. low': '17.2300', '4. close': '17.2300', '5. volume': '0'}, '2022-03-24': {'1. open': '17.3800', '2. high': '17.3800', '3. low': '17.3800', '4. close': '17.3800', '5. volume': '0'}, '2022-03-23': {'1. open': '17.2900', '2. high': '17.2900', '3. low': '17.2900', '4. close': '17.2900', '5. volume': '0'}, '2022-03-22': {'1. open': '17.3100', '2. high': '17.3100', '3. low': '17.3100', '4. close': '17.3100', '5. volume': '0'}, '2022-03-21': {'1. open': '17.0500', '2. high': '17.0500', '3. low': '17.0500', '4. close': '17.0500', '5. volume': '0'}, '2022-03-18': {'1. open': '17.2400', '2. high': '17.2400', '3. low': '17.2400', '4. close': '17.2400', '5. volume': '0'}, '2022-03-17': {'1. open': '17.0500', '2. high': '17.0500', '3. low': '17.0500', '4. close': '17.0500', '5. volume': '0'}, '2022-03-16': {'1. open': '16.6500', '2. high': '16.6500', '3. low': '16.6500', '4. close': '16.6500', '5. volume': '0'}, '2022-03-15': {'1. open': '15.7900', '2. high': '15.7900', '3. low': '15.7900', '4. close': '15.7900', '5. volume': '0'}, '2022-03-14': {'1. open': '16.0500', '2. high': '16.0500', '3. low': '16.0500', '4. close': '16.0500', '5. volume': '0'}, '2022-03-11': {'1. open': '16.4500', '2. high': '16.4500', '3. low': '16.4500', '4. close': '16.4500', '5. volume': '0'}, '2022-03-10': {'1. open': '16.6800', '2. high': '16.6800', '3. low': '16.6800', '4. close': '16.6800', '5. volume': '0'}, '2022-03-09': {'1. open': '16.7000', '2. high': '16.7000', '3. low': '16.7000', '4. close': '16.7000', '5. volume': '0'}, '2022-03-08': {'1. open': '16.4100', '2. high': '16.4100', '3. low': '16.4100', '4. close': '16.4100', '5. volume': '0'}, '2022-03-07': {'1. open': '16.5100', '2. high': '16.5100', '3. low': '16.5100', '4. close': '16.5100', '5. volume': '0'}, '2022-03-04': {'1. open': '17.1000', '2. high': '17.1000', '3. low': '17.1000', '4. close': '17.1000', '5. volume': '0'}, '2022-03-03': {'1. open': '17.4400', '2. high': '17.4400', '3. low': '17.4400', '4. close': '17.4400', '5. volume': '0'}, '2022-03-02': {'1. open': '17.5100', '2. high': '17.5100', '3. low': '17.5100', '4. close': '17.5100', '5. volume': '0'}, '2022-03-01': {'1. open': '17.5800', '2. high': '17.5800', '3. low': '17.5800', '4. close': '17.5800', '5. volume': '0'}, '2022-02-28': {'1. open': '17.7100', '2. high': '17.7100', '3. low': '17.7100', '4. close': '17.7100', '5. volume': '0'}, '2022-02-25': {'1. open': '18.0000', '2. high': '18.0000', '3. low': '18.0000', '4. close': '18.0000', '5. volume': '0'}, '2022-02-24': {'1. open': '17.7600', '2. high': '17.7600', '3. low': '17.7600', '4. close': '17.7600', '5. volume': '0'}, '2022-02-23': {'1. open': '18.3000', '2. high': '18.3000', '3. low': '18.3000', '4. close': '18.3000', '5. volume': '0'}, '2022-02-22': {'1. open': '18.4700', '2. high': '18.4700', '3. low': '18.4700', '4. close': '18.4700', '5. volume': '0'}, '2022-02-18': {'1. open': '18.7800', '2. high': '18.7800', '3. low': '18.7800', '4. close': '18.7800', '5. volume': '0'}, '2022-02-17': {'1. open': '18.9200', '2. high': '18.9200', '3. low': '18.9200', '4. close': '18.9200', '5. volume': '0'}, '2022-02-16': {'1. open': '19.0800', '2. high': '19.0800', '3. low': '19.0800', '4. close': '19.0800', '5. volume': '0'}, '2022-02-15': {'1. open': '18.9700', '2. high': '18.9700', '3. low': '18.9700', '4. close': '18.9700', '5. volume': '0'}, '2022-02-14': {'1. open': '18.7000', '2. high': '18.7000', '3. low': '18.7000', '4. close': '18.7000', '5. volume': '0'}, '2022-02-11': {'1. open': '18.9100', '2. high': '18.9100', '3. low': '18.9100', '4. close': '18.9100', '5. volume': '0'}, '2022-02-10': {'1. open': '19.1100', '2. high': '19.1100', '3. low': '19.1100', '4. close': '19.1100', '5. volume': '0'}, '2022-02-09': {'1. open': '19.1400', '2. high': '19.1400', '3. low': '19.1400', '4. close': '19.1400', '5. volume': '0'}, '2022-02-08': {'1. open': '18.8200', '2. high': '18.8200', '3. low': '18.8200', '4. close': '18.8200', '5. volume': '0'}, '2022-02-07': {'1. open': '18.6800', '2. high': '18.6800', '3. low': '18.6800', '4. close': '18.6800', '5. volume': '0'}, '2022-02-04': {'1. open': '18.7000', '2. high': '18.7000', '3. low': '18.7000', '4. close': '18.7000', '5. volume': '0'}, '2022-02-03': {'1. open': '18.5200', '2. high': '18.5200', '3. low': '18.5200', '4. close': '18.5200', '5. volume': '0'}, '2022-02-02': {'1. open': '18.7700', '2. high': '18.7700', '3. low': '18.7700', '4. close': '18.7700', '5. volume': '0'}, '2022-02-01': {'1. open': '18.7400', '2. high': '18.7400', '3. low': '18.7400', '4. close': '18.7400', '5. volume': '0'}, '2022-01-31': {'1. open': '18.6500', '2. high': '18.6500', '3. low': '18.6500', '4. close': '18.6500', '5. volume': '0'}, '2022-01-28': {'1. open': '18.2900', '2. high': '18.2900', '3. low': '18.2900', '4. close': '18.2900', '5. volume': '0'}, '2022-01-27': {'1. open': '18.1800', '2. high': '18.1800', '3. low': '18.1800', '4. close': '18.1800', '5. volume': '0'}, '2022-01-26': {'1. open': '18.3400', '2. high': '18.3400', '3. low': '18.3400', '4. close': '18.3400', '5. volume': '0'}, '2022-01-25': {'1. open': '18.3800', '2. high': '18.3800', '3. low': '18.3800', '4. close': '18.3800', '5. volume': '0'}, '2022-01-24': {'1. open': '18.5000', '2. high': '18.5000', '3. low': '18.5000', '4. close': '18.5000', '5. volume': '0'}, '2022-01-21': {'1. open': '18.7200', '2. high': '18.7200', '3. low': '18.7200', '4. close': '18.7200', '5. volume': '0'}, '2022-01-20': {'1. open': '18.9500', '2. high': '18.9500', '3. low': '18.9500', '4. close': '18.9500', '5. volume': '0'}, '2022-01-19': {'1. open': '18.9100', '2. high': '18.9100', '3. low': '18.9100', '4. close': '18.9100', '5. volume': '0'}, '2022-01-18': {'1. open': '18.8300', '2. high': '18.8300', '3. low': '18.8300', '4. close': '18.8300', '5. volume': '0'}, '2022-01-14': {'1. open': '19.1500', '2. high': '19.1500', '3. low': '19.1500', '4. close': '19.1500', '5. volume': '0'}, '2022-01-13': {'1. open': '19.1300', '2. high': '19.1300', '3. low': '19.1300', '4. close': '19.1300', '5. volume': '0'}, '2022-01-12': {'1. open': '19.2900', '2. high': '19.2900', '3. low': '19.2900', '4. close': '19.2900', '5. volume': '0'}, '2022-01-11': {'1. open': '19.0300', '2. high': '19.0300', '3. low': '19.0300', '4. close': '19.0300', '5. volume': '0'}, '2022-01-10': {'1. open': '18.7300', '2. high': '18.7300', '3. low': '18.7300', '4. close': '18.7300', '5. volume': '0'}, '2022-01-07': {'1. open': '18.6600', '2. high': '18.6600', '3. low': '18.6600', '4. close': '18.6600', '5. volume': '0'}, '2022-01-06': {'1. open': '18.5600', '2. high': '18.5600', '3. low': '18.5600', '4. close': '18.5600', '5. volume': '0'}, '2022-01-05': {'1. open': '18.5200', '2. high': '18.5200', '3. low': '18.5200', '4. close': '18.5200', '5. volume': '0'}, '2022-01-04': {'1. open': '18.8200', '2. high': '18.8200', '3. low': '18.8200', '4. close': '18.8200', '5. volume': '0'}, '2022-01-03': {'1. open': '18.8000', '2. high': '18.8000', '3. low': '18.8000', '4. close': '18.8000', '5. volume': '0'}, '2021-12-31': {'1. open': '18.7200', '2. high': '18.7200', '3. low': '18.7200', '4. close': '18.7200', '5. volume': '0'}, '2021-12-30': {'1. open': '18.6600', '2. high': '18.6600', '3. low': '18.6600', '4. close': '18.6600', '5. volume': '0'}, '2021-12-29': {'1. open': '18.5800', '2. high': '18.5800', '3. low': '18.5800', '4. close': '18.5800', '5. volume': '0'}, '2021-12-28': {'1. open': '18.6900', '2. high': '18.6900', '3. low': '18.6900', '4. close': '18.6900', '5. volume': '0'}, '2021-12-27': {'1. open': '18.7000', '2. high': '18.7000', '3. low': '18.7000', '4. close': '18.7000', '5. volume': '0'}, '2021-12-23': {'1. open': '18.6300', '2. high': '18.6300', '3. low': '18.6300', '4. close': '18.6300', '5. volume': '0'}, '2021-12-22': {'1. open': '18.5200', '2. high': '18.5200', '3. low': '18.5200', '4. close': '18.5200', '5. volume': '0'}, '2021-12-21': {'1. open': '18.4300', '2. high': '18.4300', '3. low': '18.4300', '4. close': '18.4300', '5. volume': '0'}, '2021-12-20': {'1. open': '18.1500', '2. high': '18.1500', '3. low': '18.1500', '4. close': '18.1500', '5. volume': '0'}, '2021-12-17': {'1. open': '18.4500', '2. high': '18.4500', '3. low': '18.4500', '4. close': '18.4500', '5. volume': '0'}, '2021-12-16': {'1. open': '21.1600', '2. high': '21.1600', '3. low': '21.1600', '4. close': '21.1600', '5. volume': '0'}, '2021-12-15': {'1. open': '21.1700', '2. high': '21.1700', '3. low': '21.1700', '4. close': '21.1700', '5. volume': '0'}, '2021-12-14': {'1. open': '21.1200', '2. high': '21.1200', '3. low': '21.1200', '4. close': '21.1200', '5. volume': '0'}, '2021-12-13': {'1. open': '21.1900', '2. high': '21.1900', '3. low': '21.1900', '4. close': '21.1900', '5. volume': '0'}, '2021-12-10': {'1. open': '21.4500', '2. high': '21.4500', '3. low': '21.4500', '4. close': '21.4500', '5. volume': '0'}, '2021-12-09': {'1. open': '21.5300', '2. high': '21.5300', '3. low': '21.5300', '4. close': '21.5300', '5. volume': '0'}, '2021-12-08': {'1. open': '21.4800', '2. high': '21.4800', '3. low': '21.4800', '4. close': '21.4800', '5. volume': '0'}, '2021-12-07': {'1. open': '21.4200', '2. high': '21.4200', '3. low': '21.4200', '4. close': '21.4200', '5. volume': '0'}, '2021-12-06': {'1. open': '21.0700', '2. high': '21.0700', '3. low': '21.0700', '4. close': '21.0700', '5. volume': '0'}, '2021-12-03': {'1. open': '21.0600', '2. high': '21.0600', '3. low': '21.0600', '4. close': '21.0600', '5. volume': '0'}, '2021-12-02': {'1. open': '21.3200', '2. high': '21.3200', '3. low': '21.3200', '4. close': '21.3200', '5. volume': '0'}, '2021-12-01': {'1. open': '20.9200', '2. high': '20.9200', '3. low': '20.9200', '4. close': '20.9200', '5. volume': '0'}, '2021-11-30': {'1. open': '20.8100', '2. high': '20.8100', '3. low': '20.8100', '4. close': '20.8100', '5. volume': '0'}}}

In [9]:
import pandas as pd
import requests

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=GOLD&datatype=json&apikey=DRDU0ACD89IZ5H2D'
r_stock_price = requests.get(url)
data_stock_price = r_stock_price.json()

print(data_stock_price)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'GOLD', '3. Last Refreshed': '2022-04-25', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2022-04-25': {'1. open': '22.7000', '2. high': '22.9650', '3. low': '22.2200', '4. close': '22.7300', '5. volume': '32473036'}, '2022-04-22': {'1. open': '23.5300', '2. high': '24.0900', '3. low': '23.4800', '4. close': '23.7300', '5. volume': '22036510'}, '2022-04-21': {'1. open': '24.9200', '2. high': '24.9990', '3. low': '23.8615', '4. close': '24.2200', '5. volume': '26109732'}, '2022-04-20': {'1. open': '25.0700', '2. high': '25.2900', '3. low': '24.8400', '4. close': '25.2500', '5. volume': '18808644'}, '2022-04-19': {'1. open': '25.0300', '2. high': '25.4000', '3. low': '24.7900', '4. close': '25.0100', '5. volume': '16104061'}, '2022-04-18': {'1. open': '25.5200', '2. high': '25.9900', '3. low': '25.3600', '4. close': '25.3800', '5. volume': '15103652'}, '2022-04-14': {'1. open': '25.4500', '2. high': '25.4800', '3. low': '24.9000', '4. close': '25.2000', '5. volume': '19310690'}, '2022-04-13': {'1. open': '25.6500', '2. high': '25.8650', '3. low': '25.4300', '4. close': '25.5800', '5. volume': '12520250'}, '2022-04-12': {'1. open': '25.7300', '2. high': '25.9200', '3. low': '25.3100', '4. close': '25.4400', '5. volume': '14608680'}, '2022-04-11': {'1. open': '25.7100', '2. high': '25.9100', '3. low': '25.1600', '4. close': '25.4000', '5. volume': '14707969'}, '2022-04-08': {'1. open': '24.9000', '2. high': '25.4900', '3. low': '24.9000', '4. close': '25.4100', '5. volume': '15176547'}, '2022-04-07': {'1. open': '24.6500', '2. high': '25.0600', '3. low': '24.5400', '4. close': '24.9000', '5. volume': '22827358'}, '2022-04-06': {'1. open': '24.5800', '2. high': '24.8950', '3. low': '24.3700', '4. close': '24.6100', '5. volume': '14680596'}, '2022-04-05': {'1. open': '24.9600', '2. high': '25.4800', '3. low': '24.3300', '4. close': '24.4600', '5. volume': '16890644'}, '2022-04-04': {'1. open': '25.0900', '2. high': '25.1200', '3. low': '24.5500', '4. close': '24.8600', '5. volume': '13007646'}, '2022-04-01': {'1. open': '24.3000', '2. high': '25.0150', '3. low': '24.2800', '4. close': '24.9400', '5. volume': '15554055'}, '2022-03-31': {'1. open': '24.8500', '2. high': '25.1300', '3. low': '24.5300', '4. close': '24.5300', '5. volume': '11671369'}, '2022-03-30': {'1. open': '24.6500', '2. high': '24.9384', '3. low': '24.6500', '4. close': '24.8500', '5. volume': '13921640'}, '2022-03-29': {'1. open': '23.7400', '2. high': '24.5700', '3. low': '23.6100', '4. close': '24.5300', '5. volume': '21536430'}, '2022-03-28': {'1. open': '24.1100', '2. high': '24.3200', '3. low': '23.9400', '4. close': '24.2300', '5. volume': '18905100'}, '2022-03-25': {'1. open': '24.2900', '2. high': '24.6300', '3. low': '24.1800', '4. close': '24.5400', '5. volume': '15750839'}, '2022-03-24': {'1. open': '24.7500', '2. high': '24.9600', '3. low': '24.4100', '4. close': '24.5000', '5. volume': '17732878'}, '2022-03-23': {'1. open': '24.4000', '2. high': '24.5900', '3. low': '24.1600', '4. close': '24.5700', '5. volume': '17005947'}, '2022-03-22': {'1. open': '24.2700', '2. high': '24.3900', '3. low': '23.8400', '4. close': '24.2300', '5. volume': '16200792'}, '2022-03-21': {'1. open': '23.9000', '2. high': '24.5975', '3. low': '23.8800', '4. close': '24.3000', '5. volume': '21204382'}, '2022-03-18': {'1. open': '24.1000', '2. high': '24.1500', '3. low': '23.7300', '4. close': '23.8700', '5. volume': '35716619'}, '2022-03-17': {'1. open': '23.9000', '2. high': '24.5400', '3. low': '23.8600', '4. close': '24.0800', '5. volume': '22857457'}, '2022-03-16': {'1. open': '23.5800', '2. high': '23.9400', '3. low': '23.2000', '4. close': '23.6100', '5. volume': '23974839'}, '2022-03-15': {'1. open': '22.8100', '2. high': '24.0350', '3. low': '22.8100', '4. close': '23.7700', '5. volume': '26227803'}, '2022-03-14': {'1. open': '23.7500', '2. high': '24.0100', '3. low': '23.3800', '4. close': '23.6400', '5. volume': '23139519'}, '2022-03-11': {'1. open': '23.7200', '2. high': '24.5683', '3. low': '23.4800', '4. close': '24.3500', '5. volume': '19900986'}, '2022-03-10': {'1. open': '24.4200', '2. high': '25.0150', '3. low': '24.2700', '4. close': '24.4900', '5. volume': '27099063'}, '2022-03-09': {'1. open': '23.7200', '2. high': '24.6300', '3. low': '23.4000', '4. close': '24.3300', '5. volume': '39175049'}, '2022-03-08': {'1. open': '25.0900', '2. high': '26.0700', '3. low': '24.4800', '4. close': '25.3600', '5. volume': '67227937'}, '2022-03-07': {'1. open': '24.3700', '2. high': '24.9800', '3. low': '23.9400', '4. close': '24.8600', '5. volume': '39144522'}, '2022-03-04': {'1. open': '23.7200', '2. high': '24.4800', '3. low': '23.5703', '4. close': '24.2000', '5. volume': '35859200'}, '2022-03-03': {'1. open': '23.1200', '2. high': '23.7000', '3. low': '23.1200', '4. close': '23.5700', '5. volume': '23936835'}, '2022-03-02': {'1. open': '22.8300', '2. high': '23.3600', '3. low': '22.6600', '4. close': '23.1500', '5. volume': '23287410'}, '2022-03-01': {'1. open': '22.7500', '2. high': '23.5000', '3. low': '22.7300', '4. close': '23.4600', '5. volume': '32082860'}, '2022-02-28': {'1. open': '22.8800', '2. high': '22.9100', '3. low': '22.3301', '4. close': '22.5700', '5. volume': '23866204'}, '2022-02-25': {'1. open': '22.1600', '2. high': '22.6200', '3. low': '22.0100', '4. close': '22.5600', '5. volume': '22501999'}, '2022-02-24': {'1. open': '23.4500', '2. high': '23.5900', '3. low': '22.0900', '4. close': '22.5400', '5. volume': '53409931'}, '2022-02-23': {'1. open': '22.7000', '2. high': '23.1817', '3. low': '22.7000', '4. close': '22.8300', '5. volume': '23816458'}, '2022-02-22': {'1. open': '23.1600', '2. high': '23.4400', '3. low': '22.5600', '4. close': '22.7600', '5. volume': '29392359'}, '2022-02-18': {'1. open': '23.0100', '2. high': '23.3500', '3. low': '22.9300', '4. close': '23.1400', '5. volume': '28735672'}, '2022-02-17': {'1. open': '22.5400', '2. high': '23.4699', '3. low': '22.4100', '4. close': '23.2300', '5. volume': '46712369'}, '2022-02-16': {'1. open': '21.1400', '2. high': '22.4500', '3. low': '21.1300', '4. close': '22.2300', '5. volume': '41704445'}, '2022-02-15': {'1. open': '20.4900', '2. high': '20.7400', '3. low': '20.2900', '4. close': '20.6800', '5. volume': '22307668'}, '2022-02-14': {'1. open': '20.7300', '2. high': '21.2000', '3. low': '20.7100', '4. close': '21.0900', '5. volume': '38007929'}, '2022-02-11': {'1. open': '19.3500', '2. high': '20.8700', '3. low': '19.2899', '4. close': '20.6800', '5. volume': '32059688'}, '2022-02-10': {'1. open': '19.6600', '2. high': '19.8750', '3. low': '19.2400', '4. close': '19.3000', '5. volume': '15490791'}, '2022-02-09': {'1. open': '19.8850', '2. high': '19.9750', '3. low': '19.7000', '4. close': '19.7300', '5. volume': '11394131'}, '2022-02-08': {'1. open': '19.6200', '2. high': '19.8200', '3. low': '19.5350', '4. close': '19.8200', '5. volume': '13731930'}, '2022-02-07': {'1. open': '19.3400', '2. high': '19.6600', '3. low': '19.1950', '4. close': '19.5800', '5. volume': '13218336'}, '2022-02-04': {'1. open': '18.9900', '2. high': '19.3950', '3. low': '18.9550', '4. close': '19.1900', '5. volume': '14157407'}, '2022-02-03': {'1. open': '19.1700', '2. high': '19.3000', '3. low': '18.8100', '4. close': '19.0600', '5. volume': '12239439'}, '2022-02-02': {'1. open': '19.0500', '2. high': '19.5000', '3. low': '18.8800', '4. close': '19.2200', '5. volume': '16669062'}, '2022-02-01': {'1. open': '19.1500', '2. high': '19.2899', '3. low': '18.8799', '4. close': '19.0900', '5. volume': '14344055'}, '2022-01-31': {'1. open': '18.7200', '2. high': '19.1800', '3. low': '18.5700', '4. close': '19.1500', '5. volume': '18321775'}, '2022-01-28': {'1. open': '18.5100', '2. high': '18.5900', '3. low': '18.2600', '4. close': '18.5600', '5. volume': '19097621'}, '2022-01-27': {'1. open': '18.7500', '2. high': '19.1450', '3. low': '18.6600', '4. close': '18.7100', '5. volume': '20558493'}, '2022-01-26': {'1. open': '19.3600', '2. high': '19.7157', '3. low': '18.9234', '4. close': '19.0300', '5. volume': '24282925'}, '2022-01-25': {'1. open': '19.2100', '2. high': '19.5850', '3. low': '19.1350', '4. close': '19.4900', '5. volume': '16843347'}, '2022-01-24': {'1. open': '19.2400', '2. high': '19.4100', '3. low': '18.8100', '4. close': '19.3700', '5. volume': '23942412'}, '2022-01-21': {'1. open': '20.0100', '2. high': '20.0600', '3. low': '19.2600', '4. close': '19.3400', '5. volume': '21714100'}, '2022-01-20': {'1. open': '20.1400', '2. high': '20.3000', '3. low': '19.8900', '4. close': '19.9100', '5. volume': '20414382'}, '2022-01-19': {'1. open': '18.8100', '2. high': '20.2400', '3. low': '18.7600', '4. close': '20.1700', '5. volume': '35460977'}, '2022-01-18': {'1. open': '18.5600', '2. high': '18.8450', '3. low': '18.4700', '4. close': '18.5600', '5. volume': '12936600'}, '2022-01-14': {'1. open': '18.8600', '2. high': '18.9100', '3. low': '18.5200', '4. close': '18.6800', '5. volume': '12857523'}, '2022-01-13': {'1. open': '19.1400', '2. high': '19.2900', '3. low': '18.8150', '4. close': '18.8300', '5. volume': '11928766'}, '2022-01-12': {'1. open': '18.9200', '2. high': '19.2400', '3. low': '18.7800', '4. close': '19.2000', '5. volume': '19595483'}, '2022-01-11': {'1. open': '18.6700', '2. high': '18.8800', '3. low': '18.5050', '4. close': '18.8600', '5. volume': '13712156'}, '2022-01-10': {'1. open': '18.0600', '2. high': '18.6300', '3. low': '18.0350', '4. close': '18.6200', '5. volume': '19743654'}, '2022-01-07': {'1. open': '18.0900', '2. high': '18.2200', '3. low': '17.9300', '4. close': '18.1000', '5. volume': '12787595'}, '2022-01-06': {'1. open': '18.2800', '2. high': '18.3100', '3. low': '17.9900', '4. close': '18.0200', '5. volume': '21071767'}, '2022-01-05': {'1. open': '18.9400', '2. high': '19.1000', '3. low': '18.5400', '4. close': '18.5700', '5. volume': '20273437'}, '2022-01-04': {'1. open': '18.6000', '2. high': '18.9100', '3. low': '18.5550', '4. close': '18.7300', '5. volume': '14194537'}, '2022-01-03': {'1. open': '18.7800', '2. high': '18.8000', '3. low': '18.5150', '4. close': '18.5400', '5. volume': '13001906'}, '2021-12-31': {'1. open': '18.9800', '2. high': '19.0750', '3. low': '18.7800', '4. close': '19.0000', '5. volume': '14236511'}, '2021-12-30': {'1. open': '18.4000', '2. high': '18.8900', '3. low': '18.3900', '4. close': '18.8200', '5. volume': '13570887'}, '2021-12-29': {'1. open': '18.2400', '2. high': '18.6600', '3. low': '18.2150', '4. close': '18.4000', '5. volume': '17290070'}, '2021-12-28': {'1. open': '18.4500', '2. high': '18.6650', '3. low': '18.3100', '4. close': '18.3700', '5. volume': '10311877'}, '2021-12-27': {'1. open': '18.5000', '2. high': '18.5800', '3. low': '18.2650', '4. close': '18.4100', '5. volume': '11744273'}, '2021-12-23': {'1. open': '18.4300', '2. high': '18.6900', '3. low': '18.3850', '4. close': '18.5700', '5. volume': '12163840'}, '2021-12-22': {'1. open': '18.4400', '2. high': '18.5500', '3. low': '18.1700', '4. close': '18.5300', '5. volume': '15108139'}, '2021-12-21': {'1. open': '18.4200', '2. high': '18.5100', '3. low': '18.1900', '4. close': '18.3900', '5. volume': '13909629'}, '2021-12-20': {'1. open': '18.3700', '2. high': '18.4400', '3. low': '18.0850', '4. close': '18.3300', '5. volume': '17682405'}, '2021-12-17': {'1. open': '18.5600', '2. high': '18.8500', '3. low': '18.3700', '4. close': '18.3900', '5. volume': '30832588'}, '2021-12-16': {'1. open': '17.9000', '2. high': '18.4699', '3. low': '17.8900', '4. close': '18.4400', '5. volume': '24535565'}, '2021-12-15': {'1. open': '17.8000', '2. high': '17.8300', '3. low': '17.2700', '4. close': '17.6500', '5. volume': '26972675'}, '2021-12-14': {'1. open': '17.7000', '2. high': '18.0200', '3. low': '17.6600', '4. close': '17.8600', '5. volume': '15063690'}, '2021-12-13': {'1. open': '18.0000', '2. high': '18.1500', '3. low': '17.8500', '4. close': '17.9700', '5. volume': '18505140'}, '2021-12-10': {'1. open': '18.2400', '2. high': '18.2600', '3. low': '17.9200', '4. close': '17.9500', '5. volume': '15615408'}, '2021-12-09': {'1. open': '18.3200', '2. high': '18.3900', '3. low': '18.0250', '4. close': '18.1700', '5. volume': '15593450'}, '2021-12-08': {'1. open': '18.4800', '2. high': '18.6600', '3. low': '18.3500', '4. close': '18.6000', '5. volume': '10306067'}, '2021-12-07': {'1. open': '18.5100', '2. high': '18.7400', '3. low': '18.4100', '4. close': '18.5600', '5. volume': '15898820'}, '2021-12-06': {'1. open': '18.1100', '2. high': '18.5450', '3. low': '18.0300', '4. close': '18.4900', '5. volume': '17623903'}, '2021-12-03': {'1. open': '18.2000', '2. high': '18.2600', '3. low': '17.8300', '4. close': '18.2200', '5. volume': '22027123'}, '2021-12-02': {'1. open': '18.3600', '2. high': '18.3900', '3. low': '17.9400', '4. close': '18.1800', '5. volume': '23330253'}, '2021-12-01': {'1. open': '19.0900', '2. high': '19.4371', '3. low': '18.3800', '4. close': '18.3900', '5. volume': '20580283'}}}