In [8]:
import pandas as pd
import json
import requests
import matplotlib.pyplot as plt

#### Read Covid19 Confirm case csv file

In [3]:
df_covid_confirm = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
df_covid_confirm

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/15/22,4/16/22,4/17/22,4/18/22,4/19/22,4/20/22,4/21/22,4/22/22,4/23/22,4/24/22
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,178373,178387,178418,178457,178513,178574,178611,178638,178648,178689
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,274429,274462,274504,274520,274535,274606,274606,274737,274791,274828
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,265738,265739,265739,265741,265746,265746,265754,265761,265761,265767
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,40709,40709,40709,40709,40709,41013,41013,41013,41013,41013
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,99194,99194,99194,99194,99287,99287,99287,99287,99287,99287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,656617,656617,656617,656617,656876,656876,656876,656876,656876,656876
280,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
281,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11817,11817,11817,11818,11818,11818,11818,11818,11818,11818
282,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,318404,318467,318515,318515,318640,318640,318984,318984,318984,318984
283,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,247237,247237,247278,247297,247297,247336,247383,247488,247524,247524

#### Read Covid19 Death csv file

In [4]:
df_covid_death = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
df_covid_death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/15/22,4/16/22,4/17/22,4/18/22,4/19/22,4/20/22,4/21/22,4/22/22,4/23/22,4/24/22
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7676,7676,7678,7679,7680,7680,7680,7680,7681,7682
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3495,3496,3496,3496,3496,3496,3496,3496,3496,3496
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6874,6874,6874,6874,6874,6874,6874,6874,6874,6875
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,153,153,153,153,153,153,153,153,153,153
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5656,5656,5656,5656,5657,5657,5657,5657,5657,5657
280,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
281,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2148,2148,2148,2148,2148,2148,2148,2148,2148,2149
282,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,3970,3973,3973,3973,3973,3973,3974,3974,3974,3974
283,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5462,5462,5463,5464,5464,5466,5467,5468,5468,5468

### Create new data frame by combining both confirm and death data frames

In [89]:
df_conf_and_death = df_covid_confirm + df_covid_death
mdf = df_conf_and_death[:, 0:4 ]
mdf

TypeError: '(slice(None, None, None), slice('Province/State', 'Long', None))' is an invalid key

In [84]:
mydf = df_covid_confirm['Country/Region'].unique()
mydf

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Diamond Princess', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Korea, South', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'MS Zaandam', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova',
       'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Summer Olympics 2020', 'Suriname',
       'Sweden', 'Switzerland', 'Syria', 'Taiwan*', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'US', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'West Bank and Gaza', 'Winter Olympics 2022', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [65]:
columnlist = df_conf_and_death.columns.values.tolist()
colms = columnlist[4:]
colms.insert(0,"Name")
colms.insert(1,"Symbol")
colms

['Name',
 'Symbol',
 '1/22/20',
 '1/23/20',
 '1/24/20',
 '1/25/20',
 '1/26/20',
 '1/27/20',
 '1/28/20',
 '1/29/20',
 '1/30/20',
 '1/31/20',
 '2/1/20',
 '2/2/20',
 '2/3/20',
 '2/4/20',
 '2/5/20',
 '2/6/20',
 '2/7/20',
 '2/8/20',
 '2/9/20',
 '2/10/20',
 '2/11/20',
 '2/12/20',
 '2/13/20',
 '2/14/20',
 '2/15/20',
 '2/16/20',
 '2/17/20',
 '2/18/20',
 '2/19/20',
 '2/20/20',
 '2/21/20',
 '2/22/20',
 '2/23/20',
 '2/24/20',
 '2/25/20',
 '2/26/20',
 '2/27/20',
 '2/28/20',
 '2/29/20',
 '3/1/20',
 '3/2/20',
 '3/3/20',
 '3/4/20',
 '3/5/20',
 '3/6/20',
 '3/7/20',
 '3/8/20',
 '3/9/20',
 '3/10/20',
 '3/11/20',
 '3/12/20',
 '3/13/20',
 '3/14/20',
 '3/15/20',
 '3/16/20',
 '3/17/20',
 '3/18/20',
 '3/19/20',
 '3/20/20',
 '3/21/20',
 '3/22/20',
 '3/23/20',
 '3/24/20',
 '3/25/20',
 '3/26/20',
 '3/27/20',
 '3/28/20',
 '3/29/20',
 '3/30/20',
 '3/31/20',
 '4/1/20',
 '4/2/20',
 '4/3/20',
 '4/4/20',
 '4/5/20',
 '4/6/20',
 '4/7/20',
 '4/8/20',
 '4/9/20',
 '4/10/20',
 '4/11/20',
 '4/12/20',
 '4/13/20',
 '4/14/20',
 '4/15/20',
 '4/16/20',
 '4/17/20',
 '4/18/20',
 '4/19/20',
 '4/20/20',
 '4/21/20',
 '4/22/20',
 '4/23/20',
 '4/24/20',
 '4/25/20',
 '4/26/20',
 '4/27/20',
 '4/28/20',
 '4/29/20',
 '4/30/20',
 '5/1/20',
 '5/2/20',
 '5/3/20',
 '5/4/20',
 '5/5/20',
 '5/6/20',
 '5/7/20',
 '5/8/20',
 '5/9/20',
 '5/10/20',
 '5/11/20',
 '5/12/20',
 '5/13/20',
 '5/14/20',
 '5/15/20',
 '5/16/20',
 '5/17/20',
 '5/18/20',
 '5/19/20',
 '5/20/20',
 '5/21/20',
 '5/22/20',
 '5/23/20',
 '5/24/20',
 '5/25/20',
 '5/26/20',
 '5/27/20',
 '5/28/20',
 '5/29/20',
 '5/30/20',
 '5/31/20',
 '6/1/20',
 '6/2/20',
 '6/3/20',
 '6/4/20',
 '6/5/20',
 '6/6/20',
 '6/7/20',
 '6/8/20',
 '6/9/20',
 '6/10/20',
 '6/11/20',
 '6/12/20',
 '6/13/20',
 '6/14/20',
 '6/15/20',
 '6/16/20',
 '6/17/20',
 '6/18/20',
 '6/19/20',
 '6/20/20',
 '6/21/20',
 '6/22/20',
 '6/23/20',
 '6/24/20',
 '6/25/20',
 '6/26/20',
 '6/27/20',
 '6/28/20',
 '6/29/20',
 '6/30/20',
 '7/1/20',
 '7/2/20',
 '7/3/20',
 '7/4/20',
 '7/5/20',
 '7/6/20',
 '7/7/20',
 '7/8/20',
 '7/9/20',
 '7/10/20',
 '7/11/20',
 '7/12/20',
 '7/13/20',
 '7/14/20',
 '7/15/20',
 '7/16/20',
 '7/17/20',
 '7/18/20',
 '7/19/20',
 '7/20/20',
 '7/21/20',
 '7/22/20',
 '7/23/20',
 '7/24/20',
 '7/25/20',
 '7/26/20',
 '7/27/20',
 '7/28/20',
 '7/29/20',
 '7/30/20',
 '7/31/20',
 '8/1/20',
 '8/2/20',
 '8/3/20',
 '8/4/20',
 '8/5/20',
 '8/6/20',
 '8/7/20',
 '8/8/20',
 '8/9/20',
 '8/10/20',
 '8/11/20',
 '8/12/20',
 '8/13/20',
 '8/14/20',
 '8/15/20',
 '8/16/20',
 '8/17/20',
 '8/18/20',
 '8/19/20',
 '8/20/20',
 '8/21/20',
 '8/22/20',
 '8/23/20',
 '8/24/20',
 '8/25/20',
 '8/26/20',
 '8/27/20',
 '8/28/20',
 '8/29/20',
 '8/30/20',
 '8/31/20',
 '9/1/20',
 '9/2/20',
 '9/3/20',
 '9/4/20',
 '9/5/20',
 '9/6/20',
 '9/7/20',
 '9/8/20',
 '9/9/20',
 '9/10/20',
 '9/11/20',
 '9/12/20',
 '9/13/20',
 '9/14/20',
 '9/15/20',
 '9/16/20',
 '9/17/20',
 '9/18/20',
 '9/19/20',
 '9/20/20',
 '9/21/20',
 '9/22/20',
 '9/23/20',
 '9/24/20',
 '9/25/20',
 '9/26/20',
 '9/27/20',
 '9/28/20',
 '9/29/20',
 '9/30/20',
 '10/1/20',
 '10/2/20',
 '10/3/20',
 '10/4/20',
 '10/5/20',
 '10/6/20',
 '10/7/20',
 '10/8/20',
 '10/9/20',
 '10/10/20',
 '10/11/20',
 '10/12/20',
 '10/13/20',
 '10/14/20',
 '10/15/20',
 '10/16/20',
 '10/17/20',
 '10/18/20',
 '10/19/20',
 '10/20/20',
 '10/21/20',
 '10/22/20',
 '10/23/20',
 '10/24/20',
 '10/25/20',
 '10/26/20',
 '10/27/20',
 '10/28/20',
 '10/29/20',
 '10/30/20',
 '10/31/20',
 '11/1/20',
 '11/2/20',
 '11/3/20',
 '11/4/20',
 '11/5/20',
 '11/6/20',
 '11/7/20',
 '11/8/20',
 '11/9/20',
 '11/10/20',
 '11/11/20',
 '11/12/20',
 '11/13/20',
 '11/14/20',
 '11/15/20',
 '11/16/20',
 '11/17/20',
 '11/18/20',
 '11/19/20',
 '11/20/20',
 '11/21/20',
 '11/22/20',
 '11/23/20',
 '11/24/20',
 '11/25/20',
 '11/26/20',
 '11/27/20',
 '11/28/20',
 '11/29/20',
 '11/30/20',
 '12/1/20',
 '12/2/20',
 '12/3/20',
 '12/4/20',
 '12/5/20',
 '12/6/20',
 '12/7/20',
 '12/8/20',
 '12/9/20',
 '12/10/20',
 '12/11/20',
 '12/12/20',
 '12/13/20',
 '12/14/20',
 '12/15/20',
 '12/16/20',
 '12/17/20',
 '12/18/20',
 '12/19/20',
 '12/20/20',
 '12/21/20',
 '12/22/20',
 '12/23/20',
 '12/24/20',
 '12/25/20',
 '12/26/20',
 '12/27/20',
 '12/28/20',
 '12/29/20',
 '12/30/20',
 '12/31/20',
 '1/1/21',
 '1/2/21',
 '1/3/21',
 '1/4/21',
 '1/5/21',
 '1/6/21',
 '1/7/21',
 '1/8/21',
 '1/9/21',
 '1/10/21',
 '1/11/21',
 '1/12/21',
 '1/13/21',
 '1/14/21',
 '1/15/21',
 '1/16/21',
 '1/17/21',
 '1/18/21',
 '1/19/21',
 '1/20/21',
 '1/21/21',
 '1/22/21',
 '1/23/21',
 '1/24/21',
 '1/25/21',
 '1/26/21',
 '1/27/21',
 '1/28/21',
 '1/29/21',
 '1/30/21',
 '1/31/21',
 '2/1/21',
 '2/2/21',
 '2/3/21',
 '2/4/21',
 '2/5/21',
 '2/6/21',
 '2/7/21',
 '2/8/21',
 '2/9/21',
 '2/10/21',
 '2/11/21',
 '2/12/21',
 '2/13/21',
 '2/14/21',
 '2/15/21',
 '2/16/21',
 '2/17/21',
 '2/18/21',
 '2/19/21',
 '2/20/21',
 '2/21/21',
 '2/22/21',
 '2/23/21',
 '2/24/21',
 '2/25/21',
 '2/26/21',
 '2/27/21',
 '2/28/21',
 '3/1/21',
 '3/2/21',
 '3/3/21',
 '3/4/21',
 '3/5/21',
 '3/6/21',
 '3/7/21',
 '3/8/21',
 '3/9/21',
 '3/10/21',
 '3/11/21',
 '3/12/21',
 '3/13/21',
 '3/14/21',
 '3/15/21',
 '3/16/21',
 '3/17/21',
 '3/18/21',
 '3/19/21',
 '3/20/21',
 '3/21/21',
 '3/22/21',
 '3/23/21',
 '3/24/21',
 '3/25/21',
 '3/26/21',
 '3/27/21',
 '3/28/21',
 '3/29/21',
 '3/30/21',
 '3/31/21',
 '4/1/21',
 '4/2/21',
 '4/3/21',
 '4/4/21',
 '4/5/21',
 '4/6/21',
 '4/7/21',
 '4/8/21',
 '4/9/21',
 '4/10/21',
 '4/11/21',
 '4/12/21',
 '4/13/21',
 '4/14/21',
 '4/15/21',
 '4/16/21',
 '4/17/21',
 '4/18/21',
 '4/19/21',
 '4/20/21',
 '4/21/21',
 '4/22/21',
 '4/23/21',
 '4/24/21',
 '4/25/21',
 '4/26/21',
 '4/27/21',
 '4/28/21',
 '4/29/21',
 '4/30/21',
 '5/1/21',
 '5/2/21',
 '5/3/21',
 '5/4/21',
 '5/5/21',
 '5/6/21',
 '5/7/21',
 '5/8/21',
 '5/9/21',
 '5/10/21',
 '5/11/21',
 '5/12/21',
 '5/13/21',
 '5/14/21',
 '5/15/21',
 '5/16/21',
 '5/17/21',
 '5/18/21',
 '5/19/21',
 '5/20/21',
 '5/21/21',
 '5/22/21',
 '5/23/21',
 '5/24/21',
 '5/25/21',
 '5/26/21',
 '5/27/21',
 '5/28/21',
 '5/29/21',
 '5/30/21',
 '5/31/21',
 '6/1/21',
 '6/2/21',
 '6/3/21',
 '6/4/21',
 '6/5/21',
 '6/6/21',
 '6/7/21',
 '6/8/21',
 '6/9/21',
 '6/10/21',
 '6/11/21',
 '6/12/21',
 '6/13/21',
 '6/14/21',
 '6/15/21',
 '6/16/21',
 '6/17/21',
 '6/18/21',
 '6/19/21',
 '6/20/21',
 '6/21/21',
 '6/22/21',
 '6/23/21',
 '6/24/21',
 '6/25/21',
 '6/26/21',
 '6/27/21',
 '6/28/21',
 '6/29/21',
 '6/30/21',
 '7/1/21',
 '7/2/21',
 '7/3/21',
 '7/4/21',
 '7/5/21',
 '7/6/21',
 '7/7/21',
 '7/8/21',
 '7/9/21',
 '7/10/21',
 '7/11/21',
 '7/12/21',
 '7/13/21',
 '7/14/21',
 '7/15/21',
 '7/16/21',
 '7/17/21',
 '7/18/21',
 '7/19/21',
 '7/20/21',
 '7/21/21',
 '7/22/21',
 '7/23/21',
 '7/24/21',
 '7/25/21',
 '7/26/21',
 '7/27/21',
 '7/28/21',
 '7/29/21',
 '7/30/21',
 '7/31/21',
 '8/1/21',
 '8/2/21',
 '8/3/21',
 '8/4/21',
 '8/5/21',
 '8/6/21',
 '8/7/21',
 '8/8/21',
 '8/9/21',
 '8/10/21',
 '8/11/21',
 '8/12/21',
 '8/13/21',
 '8/14/21',
 '8/15/21',
 '8/16/21',
 '8/17/21',
 '8/18/21',
 '8/19/21',
 '8/20/21',
 '8/21/21',
 '8/22/21',
 '8/23/21',
 '8/24/21',
 '8/25/21',
 '8/26/21',
 '8/27/21',
 '8/28/21',
 '8/29/21',
 '8/30/21',
 '8/31/21',
 '9/1/21',
 '9/2/21',
 '9/3/21',
 '9/4/21',
 '9/5/21',
 '9/6/21',
 '9/7/21',
 '9/8/21',
 '9/9/21',
 '9/10/21',
 '9/11/21',
 '9/12/21',
 '9/13/21',
 '9/14/21',
 '9/15/21',
 '9/16/21',
 '9/17/21',
 '9/18/21',
 '9/19/21',
 '9/20/21',
 '9/21/21',
 '9/22/21',
 '9/23/21',
 '9/24/21',
 '9/25/21',
 '9/26/21',
 '9/27/21',
 '9/28/21',
 '9/29/21',
 '9/30/21',
 '10/1/21',
 '10/2/21',
 '10/3/21',
 '10/4/21',
 '10/5/21',
 '10/6/21',
 '10/7/21',
 '10/8/21',
 '10/9/21',
 '10/10/21',
 '10/11/21',
 '10/12/21',
 '10/13/21',
 '10/14/21',
 '10/15/21',
 '10/16/21',
 '10/17/21',
 '10/18/21',
 '10/19/21',
 '10/20/21',
 '10/21/21',
 '10/22/21',
 '10/23/21',
 '10/24/21',
 '10/25/21',
 '10/26/21',
 '10/27/21',
 '10/28/21',
 '10/29/21',
 '10/30/21',
 '10/31/21',
 '11/1/21',
 '11/2/21',
 '11/3/21',
 '11/4/21',
 '11/5/21',
 '11/6/21',
 '11/7/21',
 '11/8/21',
 '11/9/21',
 '11/10/21',
 '11/11/21',
 '11/12/21',
 '11/13/21',
 '11/14/21',
 '11/15/21',
 '11/16/21',
 '11/17/21',
 '11/18/21',
 '11/19/21',
 '11/20/21',
 '11/21/21',
 '11/22/21',
 '11/23/21',
 '11/24/21',
 '11/25/21',
 '11/26/21',
 '11/27/21',
 '11/28/21',
 '11/29/21',
 '11/30/21',
 '12/1/21',
 '12/2/21',
 '12/3/21',
 '12/4/21',
 '12/5/21',
 '12/6/21',
 '12/7/21',
 '12/8/21',
 '12/9/21',
 '12/10/21',
 '12/11/21',
 '12/12/21',
 '12/13/21',
 '12/14/21',
 '12/15/21',
 '12/16/21',
 '12/17/21',
 '12/18/21',
 '12/19/21',
 '12/20/21',
 '12/21/21',
 '12/22/21',
 '12/23/21',
 '12/24/21',
 '12/25/21',
 '12/26/21',
 '12/27/21',
 '12/28/21',
 '12/29/21',
 '12/30/21',
 '12/31/21',
 '1/1/22',
 '1/2/22',
 '1/3/22',
 '1/4/22',
 '1/5/22',
 '1/6/22',
 '1/7/22',
 '1/8/22',
 '1/9/22',
 '1/10/22',
 '1/11/22',
 '1/12/22',
 '1/13/22',
 '1/14/22',
 '1/15/22',
 '1/16/22',
 '1/17/22',
 '1/18/22',
 '1/19/22',
 '1/20/22',
 '1/21/22',
 '1/22/22',
 '1/23/22',
 '1/24/22',
 '1/25/22',
 '1/26/22',
 '1/27/22',
 '1/28/22',
 '1/29/22',
 '1/30/22',
 '1/31/22',
 '2/1/22',
 '2/2/22',
 '2/3/22',
 '2/4/22',
 '2/5/22',
 '2/6/22',
 '2/7/22',
 '2/8/22',
 '2/9/22',
 '2/10/22',
 '2/11/22',
 '2/12/22',
 '2/13/22',
 '2/14/22',
 '2/15/22',
 '2/16/22',
 '2/17/22',
 '2/18/22',
 '2/19/22',
 '2/20/22',
 '2/21/22',
 '2/22/22',
 '2/23/22',
 '2/24/22',
 '2/25/22',
 '2/26/22',
 '2/27/22',
 '2/28/22',
 '3/1/22',
 '3/2/22',
 '3/3/22',
 '3/4/22',
 '3/5/22',
 '3/6/22',
 '3/7/22',
 '3/8/22',
 '3/9/22',
 '3/10/22',
 '3/11/22',
 '3/12/22',
 '3/13/22',
 '3/14/22',
 '3/15/22',
 '3/16/22',
 '3/17/22',
 '3/18/22',
 '3/19/22',
 '3/20/22',
 '3/21/22',
 '3/22/22',
 '3/23/22',
 '3/24/22',
 '3/25/22',
 '3/26/22',
 '3/27/22',
 '3/28/22',
 '3/29/22',
 '3/30/22',
 '3/31/22',
 '4/1/22',
 '4/2/22',
 '4/3/22',
 '4/4/22',
 '4/5/22',
 '4/6/22',
 '4/7/22',
 '4/8/22',
 '4/9/22',
 '4/10/22',
 '4/11/22',
 '4/12/22',
 '4/13/22',
 '4/14/22',
 '4/15/22',
 '4/16/22',
 '4/17/22',
 '4/18/22',
 '4/19/22',
 '4/20/22',
 '4/21/22',
 '4/22/22',
 '4/23/22',
 '4/24/22']

#### Prepare Americal Stock List From AlphaVantage API

In [ ]:
df_usa_stocks = pd.read_csv('stock_data/american_stocks.csv',header=0)
df_usa_stocks

base_url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol='
api_key = '&apikey=' + 'P5R3380DQ77VJ1VM'

usa_stock_list=[]

usa_stock_json = {
    "Name":[],
    "Symbol":[],
    "Details":[]
}


date_column_list = df_conf_and_death.columns.values.tolist()
date_columns = date_column_list[4:]
date_columns.insert(0,"Name")
date_columns.insert(1,"Symbol")


usa_stock_df_json = {}

# AlphaVantage API to get stock details
for stock_name, stock in zip(df_usa_stocks['Name'],df_usa_stocks['Symbol']):    
    url = base_url + stock + api_key
    resp = requests.get(url)
    data = resp.json()
    usa_stock_df_json[]
    usa_stock_df_json['Name'].append(stock_name)
    usa_stock_df_json['Symbol'].append(stock)
    stock_details = data['Time Series (Daily)']

    for stock_detail in stock_details:
        usa_stock_df_json['Date'].append(stock_detail)
        usa_stock_df_json['Hight'].append(stock_details[stock_detail]['1. open'])
        usa_stock_df_json['Low'].append(stock_details[stock_detail]['2. high'])
        usa_stock_df_json['Open'].append(stock_details[stock_detail]['3. low'])
        usa_stock_df_json['Close'].append(stock_details[stock_detail]['4. close'])
        usa_stock_df_json['Volume'].append(stock_details[stock_detail]['5. volume'])



print(usa_stock_df_json)

In [50]:
len(usa_stock_df_json['Low'])

200

#### Create American stocks Data Frame

In [26]:
usa_stock_df_json = {
    'Name':[],
    'Symbol':[],
    'Date':[],
    'Hight':[],
    'Low':[],
    'Open':[],
    'Close':[],
    'Volume':[]
}

In [40]:
#print(json.dumps(usa_stock_json['Details'][0],indent=4))
mydata = usa_stock_json['Details'][0]['Time Series (Daily)']

for d in mydata:
    print(d)
    print(mydata[d])
#data = usa_stock_json['Details'][0]['Time Series (Daily)']['2022-04-25']
#print(data)

2022-04-25
{'1. open': '161.1200', '2. high': '163.1700', '3. low': '158.4600', '4. close': '162.8800', '5. volume': '96046376'}
2022-04-22
{'1. open': '166.4600', '2. high': '167.8699', '3. low': '161.5000', '4. close': '161.7900', '5. volume': '84882424'}
2022-04-21
{'1. open': '168.9100', '2. high': '171.5300', '3. low': '165.9100', '4. close': '166.4200', '5. volume': '87227768'}
2022-04-20
{'1. open': '168.7600', '2. high': '168.8800', '3. low': '166.1000', '4. close': '167.2300', '5. volume': '67718110'}
2022-04-19
{'1. open': '165.0200', '2. high': '167.8200', '3. low': '163.9100', '4. close': '167.4000', '5. volume': '67723833'}
2022-04-18
{'1. open': '163.9200', '2. high': '166.5984', '3. low': '163.5700', '4. close': '165.0700', '5. volume': '69023941'}
2022-04-14
{'1. open': '170.6200', '2. high': '171.2700', '3. low': '165.0400', '4. close': '165.2900', '5. volume': '75329376'}
2022-04-13
{'1. open': '167.3900', '2. high': '171.0400', '3. low': '166.7700', '4. close': '170.4000', '5. volume': '70618925'}
2022-04-12
{'1. open': '168.0200', '2. high': '169.8700', '3. low': '166.6400', '4. close': '167.6600', '5. volume': '79265181'}
2022-04-11
{'1. open': '168.7100', '2. high': '169.0300', '3. low': '165.5000', '4. close': '165.7500', '5. volume': '72246706'}
2022-04-08
{'1. open': '171.7800', '2. high': '171.7800', '3. low': '169.2000', '4. close': '170.0900', '5. volume': '76575508'}
2022-04-07
{'1. open': '171.1600', '2. high': '173.3600', '3. low': '169.8500', '4. close': '172.1400', '5. volume': '77594650'}
2022-04-06
{'1. open': '172.3600', '2. high': '173.6300', '3. low': '170.1300', '4. close': '171.8300', '5. volume': '89058782'}
2022-04-05
{'1. open': '177.5000', '2. high': '178.3000', '3. low': '174.4150', '4. close': '175.0600', '5. volume': '70902999'}
2022-04-04
{'1. open': '174.5700', '2. high': '178.4900', '3. low': '174.4400', '4. close': '178.4400', '5. volume': '76545983'}
2022-04-01
{'1. open': '174.0300', '2. high': '174.8800', '3. low': '171.9400', '4. close': '174.3100', '5. volume': '78751328'}
2022-03-31
{'1. open': '177.8400', '2. high': '178.0300', '3. low': '174.4000', '4. close': '174.6100', '5. volume': '103049285'}
2022-03-30
{'1. open': '178.5500', '2. high': '179.6100', '3. low': '176.7000', '4. close': '177.7700', '5. volume': '92633154'}
2022-03-29
{'1. open': '176.6900', '2. high': '179.0100', '3. low': '176.3400', '4. close': '178.9600', '5. volume': '100589440'}
2022-03-28
{'1. open': '172.1700', '2. high': '175.7300', '3. low': '172.0000', '4. close': '175.6000', '5. volume': '90371916'}
2022-03-25
{'1. open': '173.8800', '2. high': '175.2800', '3. low': '172.7500', '4. close': '174.7200', '5. volume': '80281664'}
2022-03-24
{'1. open': '171.0600', '2. high': '174.1400', '3. low': '170.2100', '4. close': '174.0700', '5. volume': '90131418'}
2022-03-23
{'1. open': '167.9900', '2. high': '172.6400', '3. low': '167.6500', '4. close': '170.2100', '5. volume': '98062674'}
2022-03-22
{'1. open': '165.5100', '2. high': '169.4200', '3. low': '164.9100', '4. close': '168.8200', '5. volume': '80979755'}
2022-03-21
{'1. open': '163.5100', '2. high': '166.3500', '3. low': '163.0150', '4. close': '165.3800', '5. volume': '89029269'}
2022-03-18
{'1. open': '160.5100', '2. high': '164.4800', '3. low': '159.7600', '4. close': '163.9800', '5. volume': '122055535'}
2022-03-17
{'1. open': '158.6100', '2. high': '161.0000', '3. low': '157.6300', '4. close': '160.6200', '5. volume': '75615376'}
2022-03-16
{'1. open': '157.0500', '2. high': '160.0000', '3. low': '154.4600', '4. close': '159.5900', '5. volume': '102300157'}
2022-03-15
{'1. open': '150.9000', '2. high': '155.5700', '3. low': '150.3800', '4. close': '155.0900', '5. volume': '92964302'}
2022-03-14
{'1. open': '151.4500', '2. high': '154.1200', '3. low': '150.1000', '4. close': '150.6200', '5. volume': '108732111'}
2022-03-11
{'1. open': '158.9300', '2. high': '159.2800', '3. low': '154.5000', '4. close': '154.7300', '5. volume': '96970102'}
2022-03-10
{'1. open': '160.2000', '2. high': '160.3900', '3. low': '155.9800', '4. close': '158.5200', '5. volume': '105342033'}
2022-03-09
{'1. open': '161.4750', '2. high': '163.4100', '3. low': '159.4100', '4. close': '162.9500', '5. volume': '91454905'}
2022-03-08
{'1. open': '158.8200', '2. high': '162.8800', '3. low': '155.8000', '4. close': '157.4400', '5. volume': '131148280'}
2022-03-07
{'1. open': '163.3600', '2. high': '165.0200', '3. low': '159.0400', '4. close': '159.3000', '5. volume': '96418845'}
2022-03-04
{'1. open': '164.4900', '2. high': '165.5500', '3. low': '162.1000', '4. close': '163.1700', '5. volume': '83819592'}
2022-03-03
{'1. open': '168.4700', '2. high': '168.9100', '3. low': '165.5500', '4. close': '166.2300', '5. volume': '76678441'}
2022-03-02
{'1. open': '164.3900', '2. high': '167.3600', '3. low': '162.9500', '4. close': '166.5600', '5. volume': '79724750'}
2022-03-01
{'1. open': '164.6950', '2. high': '166.6000', '3. low': '161.9700', '4. close': '163.2000', '5. volume': '83474425'}
2022-02-28
{'1. open': '163.0600', '2. high': '165.4200', '3. low': '162.4300', '4. close': '165.1200', '5. volume': '95056629'}
2022-02-25
{'1. open': '163.8400', '2. high': '165.1200', '3. low': '160.8738', '4. close': '164.8500', '5. volume': '91974222'}
2022-02-24
{'1. open': '152.5800', '2. high': '162.8500', '3. low': '152.0000', '4. close': '162.7400', '5. volume': '141147540'}
2022-02-23
{'1. open': '165.5400', '2. high': '166.1500', '3. low': '159.7500', '4. close': '160.0700', '5. volume': '90009247'}
2022-02-22
{'1. open': '164.9800', '2. high': '166.6900', '3. low': '162.1500', '4. close': '164.3200', '5. volume': '90457637'}
2022-02-18
{'1. open': '169.8200', '2. high': '170.5413', '3. low': '166.1900', '4. close': '167.3000', '5. volume': '82772674'}
2022-02-17
{'1. open': '171.0300', '2. high': '171.9100', '3. low': '168.4700', '4. close': '168.8800', '5. volume': '69589344'}
2022-02-16
{'1. open': '171.8500', '2. high': '173.3400', '3. low': '170.0500', '4. close': '172.5500', '5. volume': '61177398'}
2022-02-15
{'1. open': '170.9700', '2. high': '172.9500', '3. low': '170.2500', '4. close': '172.7900', '5. volume': '64286320'}
2022-02-14
{'1. open': '167.3700', '2. high': '169.5800', '3. low': '166.5600', '4. close': '168.8800', '5. volume': '86185530'}
2022-02-11
{'1. open': '172.3300', '2. high': '173.0800', '3. low': '168.0400', '4. close': '168.6400', '5. volume': '98670687'}
2022-02-10
{'1. open': '174.1400', '2. high': '175.4800', '3. low': '171.5500', '4. close': '172.1200', '5. volume': '90865899'}
2022-02-09
{'1. open': '176.0500', '2. high': '176.6500', '3. low': '174.9000', '4. close': '176.2800', '5. volume': '71285038'}
2022-02-08
{'1. open': '171.7300', '2. high': '175.3500', '3. low': '171.4300', '4. close': '174.8300', '5. volume': '74829217'}
2022-02-07
{'1. open': '172.8600', '2. high': '173.9458', '3. low': '170.9500', '4. close': '171.6600', '5. volume': '77251204'}
2022-02-04
{'1. open': '171.6800', '2. high': '174.1000', '3. low': '170.6800', '4. close': '172.3900', '5. volume': '82465400'}
2022-02-03
{'1. open': '174.4800', '2. high': '176.2399', '3. low': '172.1200', '4. close': '172.9000', '5. volume': '89418074'}
2022-02-02
{'1. open': '174.7450', '2. high': '175.8800', '3. low': '173.3300', '4. close': '175.8400', '5. volume': '84914256'}
2022-02-01
{'1. open': '174.0100', '2. high': '174.8400', '3. low': '172.3100', '4. close': '174.6100', '5. volume': '86213911'}
2022-01-31
{'1. open': '170.1600', '2. high': '175.0000', '3. low': '169.5100', '4. close': '174.7800', '5. volume': '115541590'}
2022-01-28
{'1. open': '165.7100', '2. high': '170.3500', '3. low': '162.8000', '4. close': '170.3300', '5. volume': '179935660'}
2022-01-27
{'1. open': '162.4500', '2. high': '163.8400', '3. low': '158.2800', '4. close': '159.2200', '5. volume': '121954638'}
2022-01-26
{'1. open': '163.5000', '2. high': '164.3894', '3. low': '157.8200', '4. close': '159.6900', '5. volume': '108275308'}
2022-01-25
{'1. open': '158.9800', '2. high': '162.7600', '3. low': '157.0200', '4. close': '159.7800', '5. volume': '115798367'}
2022-01-24
{'1. open': '160.0200', '2. high': '162.3000', '3. low': '154.7000', '4. close': '161.6200', '5. volume': '162706686'}
2022-01-21
{'1. open': '164.4150', '2. high': '166.3300', '3. low': '162.3000', '4. close': '162.4100', '5. volume': '122848858'}
2022-01-20
{'1. open': '166.9800', '2. high': '169.6800', '3. low': '164.1800', '4. close': '164.5100', '5. volume': '91420515'}
2022-01-19
{'1. open': '170.0000', '2. high': '171.0800', '3. low': '165.9400', '4. close': '166.2300', '5. volume': '92914792'}
2022-01-18
{'1. open': '171.5100', '2. high': '172.5400', '3. low': '169.4050', '4. close': '169.8000', '5. volume': '90500236'}
2022-01-14
{'1. open': '171.3400', '2. high': '173.7800', '3. low': '171.0900', '4. close': '173.0700', '5. volume': '80440780'}
2022-01-13
{'1. open': '175.7800', '2. high': '176.6200', '3. low': '171.7900', '4. close': '172.1900', '5. volume': '84505760'}
2022-01-12
{'1. open': '176.1200', '2. high': '177.1800', '3. low': '174.8200', '4. close': '175.5300', '5. volume': '74805173'}
2022-01-11
{'1. open': '172.3200', '2. high': '175.1800', '3. low': '170.8200', '4. close': '175.0800', '5. volume': '75937685'}
2022-01-10
{'1. open': '169.0800', '2. high': '172.5000', '3. low': '168.1700', '4. close': '172.1900', '5. volume': '106765552'}
2022-01-07
{'1. open': '172.8900', '2. high': '174.1400', '3. low': '171.0300', '4. close': '172.1700', '5. volume': '86709147'}
2022-01-06
{'1. open': '172.7000', '2. high': '175.3000', '3. low': '171.6400', '4. close': '172.0000', '5. volume': '96903955'}
2022-01-05
{'1. open': '179.6100', '2. high': '180.1700', '3. low': '174.6400', '4. close': '174.9200', '5. volume': '94537602'}
2022-01-04
{'1. open': '182.6300', '2. high': '182.9400', '3. low': '179.1200', '4. close': '179.7000', '5. volume': '99310438'}
2022-01-03
{'1. open': '177.8300', '2. high': '182.8800', '3. low': '177.7100', '4. close': '182.0100', '5. volume': '104701220'}
2021-12-31
{'1. open': '178.0850', '2. high': '179.2300', '3. low': '177.2600', '4. close': '177.5700', '5. volume': '61661433'}
2021-12-30
{'1. open': '179.4700', '2. high': '180.5700', '3. low': '178.0900', '4. close': '178.2000', '5. volume': '59773014'}
2021-12-29
{'1. open': '179.3300', '2. high': '180.6300', '3. low': '178.1400', '4. close': '179.3800', '5. volume': '62348931'}
2021-12-28
{'1. open': '180.1600', '2. high': '181.3300', '3. low': '178.5300', '4. close': '179.2900', '5. volume': '79144339'}
2021-12-27
{'1. open': '177.0850', '2. high': '180.4200', '3. low': '177.0700', '4. close': '180.3300', '5. volume': '74919582'}
2021-12-23
{'1. open': '175.8500', '2. high': '176.8499', '3. low': '175.2700', '4. close': '176.2800', '5. volume': '68356567'}
2021-12-22
{'1. open': '173.0400', '2. high': '175.8600', '3. low': '172.1500', '4. close': '175.6400', '5. volume': '92135303'}
2021-12-21
{'1. open': '171.5550', '2. high': '173.2000', '3. low': '169.1200', '4. close': '172.9900', '5. volume': '91185905'}
2021-12-20
{'1. open': '168.2800', '2. high': '170.5800', '3. low': '167.4600', '4. close': '169.7500', '5. volume': '107499114'}
2021-12-17
{'1. open': '169.9300', '2. high': '173.4700', '3. low': '169.6900', '4. close': '171.1400', '5. volume': '195923441'}
2021-12-16
{'1. open': '179.2800', '2. high': '181.1400', '3. low': '170.7500', '4. close': '172.2600', '5. volume': '150185843'}
2021-12-15
{'1. open': '175.1100', '2. high': '179.5000', '3. low': '172.3108', '4. close': '179.3000', '5. volume': '131063257'}
2021-12-14
{'1. open': '175.2500', '2. high': '177.7400', '3. low': '172.2100', '4. close': '174.3300', '5. volume': '139380382'}
2021-12-13
{'1. open': '181.1150', '2. high': '182.1300', '3. low': '175.5300', '4. close': '175.7400', '5. volume': '153237019'}
2021-12-10
{'1. open': '175.2050', '2. high': '179.6300', '3. low': '174.6900', '4. close': '179.4500', '5. volume': '115402731'}
2021-12-09
{'1. open': '174.9100', '2. high': '176.7500', '3. low': '173.9200', '4. close': '174.5600', '5. volume': '108923739'}
2021-12-08
{'1. open': '172.1250', '2. high': '175.9600', '3. low': '170.7000', '4. close': '175.0800', '5. volume': '116998901'}
2021-12-07
{'1. open': '169.0800', '2. high': '171.5800', '3. low': '168.3400', '4. close': '171.1800', '5. volume': '120405352'}
2021-12-06
{'1. open': '164.2900', '2. high': '167.8799', '3. low': '164.2800', '4. close': '165.3200', '5. volume': '107496982'}
2021-12-03
{'1. open': '164.0200', '2. high': '164.9600', '3. low': '159.7200', '4. close': '161.8400', '5. volume': '118023116'}
2021-12-02
{'1. open': '158.7350', '2. high': '164.2000', '3. low': '157.8000', '4. close': '163.7600', '5. volume': '136739174'}
2021-12-01
{'1. open': '167.4800', '2. high': '170.3000', '3. low': '164.5300', '4. close': '164.7700', '5. volume': '152423003'}